### ISSUE TITLE
安卓端崩溃

### ISSUE THREAD

**Issue by cvv-student** [wangzhaode/mnn-llm#100]
同一台手机使用APK直接下载模型能够成功运行，从头运行android项目也能运行起来，下载也正常，加载会崩溃，请问是版本的问题吗，gradle plugin为3.5.3，gradle是6.5，ndk是21.4.7075529，不慎感激

**Comment by cvv-student** [comment]
我debug了一下，看到是加载block8的时候出的问题，直接崩溃，其他设置都保证默认

**Comment by cvv-student** [comment]
我debug了一下，看到是加载block的时候直接崩溃，其他设置都保证默认

**Comment by pmking1** [comment]
兄弟，这个问题解决了吗，我也遇到了

**Comment by pmking1** [comment]
@wangzhaode 大佬帮忙看下

**Comment by cvv-student** [comment]
没解决，看源码里可以设置分一部分GPU加载，调了调也没用，不知道啥情况

**Comment by sunzhe09** [comment]
我也是，在手机上加载模型的时候到了block_8的时候挂了，被kill掉了，我编译的是opencl的版本

**Comment by wangzhaode** [comment]
> 我也是，在手机上加载模型的时候到了block_8的时候挂了，被kill掉了，我编译的是opencl的版本

opencl目前在手机上跑会因为内存问题被kill 这个需要等性能优化后解决
