### ISSUE TITLE
widows 编译执行cmake --build .报错

### ISSUE THREAD

**Issue by xzh12890** [wangzhaode/mnn-llm#106]
In file included from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/ext/atomicity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/bits/ios_base.h:39,
                 from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/ios:42,
                 from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/istream:38,
                 from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/fstream:38,
                 from /cygdrive/d/ChatGLM-MNN/src/chat.cpp:9:
/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/mutex:686:32: error: too many initializers for '__gthread_once_t' {aka 'pthread_once_t'}
  686 |     __gthread_once_t _M_once = __GTHREAD_ONCE_INIT;
      |                                ^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/chat.dir/build.make:76: CMakeFiles/chat.dir/src/chat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/chat.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by wangzhaode** [comment]
READEM中windows编译时针对MSVC的；cygwin + gcc的环境需要你自己适配一下
