### ISSUE TITLE
LLM模型的onnx导出py脚本还会提供吗

### ISSUE THREAD

**Issue by zxy-zzz** [wangzhaode/mnn-llm#107]
最新版本是删除了onnx导出的脚本吗，这个脚本后面会提供吗

**Comment by wangzhaode** [comment]
提供的 现在整理了一下 提升了易用性，在这个项目中：

https://github.com/wangzhaode/llm-export

**Comment by wangzhaode** [comment]
添加到了README中

**Comment by zxy-zzz** [comment]
> 添加到了README中

谢谢
