### ISSUE TITLE
release 新版本apk

### ISSUE THREAD

**Issue by CRGBS** [wangzhaode/mnn-llm#108]
可以讓action執行完自動釋放新版本apk

**Comment by wangzhaode** [comment]
是的 正在开发中

**Comment by wangzhaode** [comment]
https://github.com/wangzhaode/mnn-llm/actions/runs/6275126344

已经支持了

**Comment by CRGBS** [comment]
看起來build之後沒有release出來

**Comment by wangzhaode** [comment]
> 看起來build之後沒有release出來 @wangzhaode

没有更新到release上 目前是加了apk构建的测试

**Comment by wangzhaode** [comment]
是的 Android apk release需要key 我会手动打包relezse出来的

可以在release中查看
