### ISSUE TITLE
咨询: onnx 模型

### ISSUE THREAD

**Issue by haolongzhangm** [wangzhaode/mnn-llm#11]
请教一下
1： ONNX 模型是怎么转换出来的
2： 看到 ONNX 模型有很多个， 几乎每一个都是  768MB， 这个 768 是有什么含义吗

**Comment by wangzhaode** [comment]
对源码做了些改动之后使用torch.onnx.export导出来的；

直接导出模型太大了，所以把模型的28层分层导出了，大小没有特殊含义，就是一层模型的参数量；

**Comment by haolongzhangm** [comment]
1： 方面开源一下 “对源码做了些改动之后” ， 这个方便开源修改部分， 我这边尝试 torch.onnx.export 时，遇到 复数问题，需要把这部分删除，才不会报复数问题
2： 在1的基础上， 在 128GB 的DDR 环境，没有export 成功，因为 OUT OF MEMORY 了， 观察到 消耗了100GB ，依然还在消耗内存
3： 这些分散的 ONNX 可以合并吗

**Comment by wangzhaode** [comment]
代码整理好之后会pr到chatglm-6b的仓库；
可以合并成一个，我刚开始导出是一个模型；

**Comment by Hap-Zhang** [comment]
@wangzhaode 
您好，请问您公布出来的onnx模型好像没有glm_block_8.onnx和glm_block_9.onnx，可以再上传下这两个模型吗？谢谢啦

**Comment by wangzhaode** [comment]
哦 这两个模型上传的有问题是嘛 我明天重新上传一下

**Comment by 18582088138** [comment]
> 哦 这两个模型上传的有问题是嘛 我明天重新上传一下
你好，貌似glm_block_8.onnx和glm_block_9.onnx 还是没有上传成功
另外想请教一下，onnx如何运行这种分段的额模型，是直接按顺序load 之后就可以使用了么？

**Comment by zhaohb** [comment]
@wangzhaode Thank you very much for your work, it is great. 
Could you send out an overall onnx model? so that we can split the model according to our needs, Thank you very much.

**Comment by liang1232018** [comment]
您好！感谢开源ChatGLM on MNN的工作！
请问一下，ONNX模型，转换成.mnn格式，是直接用的MNN提供的converter么？ 能否开源pytorch原模型到多个mnn小模型的部分的代码？

**Comment by sgxu** [comment]
你好， 我这边运行 python3 export.py 0 出现错误：
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

请问这个如何解决呢 ？

**Comment by sgxu** [comment]
你好， 请问可以提供一个转 onnx 模型的脚本吗， 就是导出一个 onnx 模型，而不是拆分成多个 onnx模型，
或者要如何把多个 onnx 模型合并成一个模型呢 ？

**Comment by sgxu** [comment]
你好， 我在转 embedding 层 to onnx 的时候遇到错误：
RuntimeError: Given normalized_shape=[4096], expected input with shape [*, 4096], but got input of size[4]

**Comment by jinluyang** [comment]
Guys, here is a script for this. 这里写了一个脚本来导出整个onnx
https://github.com/jinluyang/ChatGLM-MNN/blob/master/export_script/export_as_whole.py
注意：1、Pytorch需要高版本，否则export函数需要额外的参数，未尝试。2、导出过程需要大量的CPU内存和CPU计算。3、此onnx只是一次decoding过程，只生成一个token，而且也不支持KV-cache优化。4、导出的模型不包含采样部分，因为model.forward不包含采样部分。wangzhaode的实现同样不包括
huggingface官方提供的方法https://huggingface.co/docs/transformers/serialization#validating-the-model-outputs 首先其中没有官方实现，其次自己写onnxconfig导出的时候，貌似导出过程中未能正确生产3个dummy输入。
这个目录中使用的modeling_chatglm.py比较旧，如果更新以后会发现新版本直接使用了PretrainedModel.generate函数，使得我们通过修改modeling_chatglm.py导出onnx比较困难。我在最新的代码基础上对照这个目录下的实现进行了一些修改，从而使得可以正确导出。

**Comment by wangzhaode** [comment]
Hi, all;

现在项目里提供了导出ONNX的代码，代码将原始模型分为了embedding, glm_block x 28, lm_head；
对提供的代码稍作修改，便可以任意合并导出ONNX模型；

**Comment by YueGeek** [comment]
> Hi, all;
> 
> 现在项目里提供了导出ONNX的代码，代码将原始模型分为了embedding, glm_block x 28, lm_head； 对提供的代码稍作修改，便可以任意合并导出ONNX模型；

您好，请问可以直接使用您生成onnx模型进行推理吗？
