### ISSUE TITLE
看起來build之後沒有release出來

### ISSUE THREAD

**Issue by CRGBS** [wangzhaode/mnn-llm#110]
看起來build之後沒有release出來
@wangzhaode

_Originally posted by @CRGBS in https://github.com/wangzhaode/mnn-llm/issues/108#issuecomment-1734698497_
          
          其他環境的都有release
          只有android的沒有release出來

**Comment by wangzhaode** [comment]
是的 Android apk release需要key 我会手动打包relezse出来的
