### ISSUE TITLE
[Request For New Feature] Support InternLM Model

### ISSUE THREAD

**Issue by crazysteeaam** [wangzhaode/mnn-llm#115]
Do you have the plan to support InternLM-7B & InternLM-20B?
(https://github.com/InternLM/InternLM)
We'd love to provide technical support and other forms of assistance where needed.
Thanks!

**Comment by wangzhaode** [comment]
Support `Internlm-chat-7b` in https://github.com/wangzhaode/mnn-llm/commit/347f22ad14485936cb4d0cdb6bcff64ff744437b
