### ISSUE TITLE
Windows10、Ubuntu22、Android端编译，均报错，找不到 MNN/AutoTime.hpp 文件

### ISSUE THREAD

**Issue by ewwerpm** [wangzhaode/mnn-llm#117]
Ubuntu22 下用的  scripts/build.sh 文件编译的，我搜了一下，有 MNN/AutoTime.hpp 这个文件，但是路径设置不对，找不到。
![image](https://github.com/wangzhaode/mnn-llm/assets/25223652/2cf639a4-0e61-4047-839c-1685ef223c8e)
另外，似乎 scripts/build.sh 脚本需要修改下啊？需要下载两个git项目，可是脚本里只写了一个git clone，能行吗？或者加一个 cd .. ?谢谢，麻烦拉我进群啊。

**Comment by Pangu-Immortal** [comment]
这个库可能是抄袭的mlc-llm，你可以参考mlc-llm，文档非常完善。https://llm.mlc.ai/docs/deploy/android.html

**Comment by wangzhaode** [comment]
小白出来乱喷？好用你就去用，随便说别人抄袭，你看代码了？





------------------ 原始邮件 ------------------
发件人: Pangu-Immortal ***@***.***&gt;
发送时间: 2023年11月21日 10:03
收件人: wangzhaode/mnn-llm ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wangzhaode/mnn-llm] Windows10、Ubuntu22、Android端编译，均报错，找不到 MNN/AutoTime.hpp 文件 (Issue #117)





 
这个库可能是抄袭的mlc-llm，你可以参考mlc-llm，文档非常完善。https://llm.mlc.ai/docs/deploy/android.html

**Comment by ewwerpm** [comment]
> 这个库可能是抄袭的mlc-llm，你可以参考mlc-llm，文档非常完善。https://llm.mlc.ai/docs/deploy/android.html

看了下，你这个链接是英文的啊。英文看起来太累了。。。。我已经在Ubuntu22上跑通了，只是速度太慢，不理想啊。不知道是不是我8g内存的原因？
