### ISSUE TITLE
将MNN/AutoTime.hpp 文件（MNN文件夹）copy过去后，还是报错

### ISSUE THREAD

**Issue by ewwerpm** [wangzhaode/mnn-llm#118]
Windows10报：
![image](https://github.com/wangzhaode/mnn-llm/assets/25223652/8090a61f-bc50-464d-8748-8891cbfa3355)
Ubuntu22 报：
![image](https://github.com/wangzhaode/mnn-llm/assets/25223652/4f33f003-568c-4e11-afa2-0dcebb37c2cd)
大佬， 帮忙看看？

**Comment by wangzhaode** [comment]
ubuntu报错看起来是因为你没有编译MNN的动态库，看一下啊libs目录下有没有libMNN.so和libMNN_Express.so

**Comment by ewwerpm** [comment]
谢谢，我把 libMNN.so和libMNN_Express.so 拷贝到 /usr/local/lib 目录下，解决了。谢谢。mnn-llm  int4的模型文件，在哪里下载啊？下载地址是多少？我直接手动下算了
