### ISSUE TITLE
没有 ./download_models.sh  这个文件，这里只有一个./download_models.sh 。

### ISSUE THREAD

**Issue by Pangu-Immortal** [wangzhaode/mnn-llm#122]
没有 ./download_models.sh  这个文件
cd resource/models
# download fp16(almost no loss of precision)
./download_models.sh int4
在这个目录下面只有一个Windows脚本。
从哪里才能得到  ./download_models.sh ，或者我该如何才能下载 模型。
求助。。。

**Comment by wangzhaode** [comment]
- 下载脚本在`script/download_models.sh`
- 现在github只提供int4量化的模型了，如果需要fp16格式可以自行转换；
