### ISSUE TITLE
完全不能用，Android工程都跑不起来，脚本几乎每一步都有错误。用这个库简直恶心啊。

### ISSUE THREAD

**Issue by Pangu-Immortal** [wangzhaode/mnn-llm#124]
有谁编译成功了吗？
教程完全对不上，Linux和windows都无法编译。而且很多脚本里都在反反复复的下载ali的MNN仓库。
太累了，不用这个了。。。

**Comment by wangzhaode** [comment]
- 最新MNN的主分支有些bug下个大版本会修复；
- 开源社区欢迎提问和PR，不喜欢不要乱喷；

**Comment by ewwerpm** [comment]
我已经在Ubuntu上跑通了。MNN 有问题。MNN版本的bug。临时解决：https://github.com/alibaba/MNN/blob/master/source/backend/cpu/compute/ConvolutionFloatFactory.cpp#L52C17-L52C17
注释掉这个文件的52行
彻底解决，等MNN的下一个版本吧
