### ISSUE TITLE
android+opencl编译报错

### ISSUE THREAD

**Issue by sunzhe09** [wangzhaode/mnn-llm#125]
你好我在build_64中加入-DMNN_OPENCL之后编译过了，最后在执行android_build.sh最后的cmake的时候报错 ld：cannot find -lMNN_CL这个是啥原因？还没有支持android的opencl吗

**Comment by wangzhaode** [comment]
需要看一下MNN编译时`MNN_SEP_BUILD`是否打开：
1. 如果是`ON` 那么MNN会生成一个独立的`libMNN_CL.so`需要将这个so拷贝到mnn-llm的libs目录下，并在编译mnn-llm时增加MNN_CL的依赖；
2. 如果是`OFF`那么MNN的OpenCL功能会集成到`libMNN.so`中，不需要额外的动态库，那么在编译mnn-llm的时候不需要MNN_CL的依赖，把这个依赖从CMakeLists.txt中移除即可；

**Comment by sunzhe09** [comment]
非常感谢，我按照你的说明添加了libMNN_CL.so到libs里面，但是，在linking CXX executable cli_demo的时候报错了：CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o: In function `std::__ndk1::__fs::filesystem::status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code&)':
/home/80239864/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1914: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
是不是需要修改ndk版本，我的ndk是21

**Comment by wangzhaode** [comment]
> 非常感谢，我按照你的说明添加了libMNN_CL.so到libs里面，但是，在linking CXX executable cli_demo的时候报错了：CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o: In function `std::__ndk1::__fs::filesystem::status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code&)': /home/80239864/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1914: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)' 是不是需要修改ndk版本，我的ndk是21

如果ndk版本低的话也可以直接移除demo里的#include "CLI11.hpp" 直接用argv[0]传递一下模型路径就行
