### ISSUE TITLE
chatglm2-6b-mnn 第二次推理coredump

### ISSUE THREAD

**Issue by Moxoo** [wangzhaode/mnn-llm#128]
- cli_demo使用https://github.com/wangzhaode/mnn-llm master 分支的0af06c编译
- chatglm2-6b的mnn文件全部在这里https://github.com/wangzhaode/mnn-llm/releases/tag/chatglm2-6b-mnn 下载
- 此外，同样的cli_demo二进制，跑qwen-1.8b-mnn（https://github.com/wangzhaode/mnn-llm/releases/tag/qwen-1.8b-mnn）是ok的

第一个问题ok
第二个问题coredump：
![Q0KCZzcQE7](https://github.com/wangzhaode/mnn-llm/assets/29149490/4daeabe2-d8a5-49b6-a2c2-ba33879fa35e)
coredump堆栈：
![TDjAaEXeh5](https://github.com/wangzhaode/mnn-llm/assets/29149490/d53bd817-156a-4477-9c04-234f48db45d0)

**Comment by Moxoo** [comment]
cli_demo编译是按照这个编译的：https://github.com/wangzhaode/mnn-llm/blob/master/script/build.sh

**Comment by Moxoo** [comment]
@wangzhaode 求大佬有空帮忙看一下

**Comment by wangzhaode** [comment]
感谢提出问题~ 确实是模型导出的形状问题；
我看了下第二轮输入拼接后序列变长，某处shape计算出错了，这个问题我明天处理一下

**Comment by wangzhaode** [comment]
用最新的代码重新转换一下就行了，新的模型已经在上传中了

**Comment by Moxoo** [comment]
> 用最新的代码重新转换一下就行了，新的模型已经重新上传了

大佬，新的模型是不是`lm.mnn`和`embedding.mnn`也要重新上传，我用你新上传的模型跑了一下，不coredump了，但是推理貌似有问题，感觉像是lm或者embedding的问题
![70gA3GtEZ7](https://github.com/wangzhaode/mnn-llm/assets/29149490/105514fa-3458-427b-91e9-eb91e922f188)

**Comment by wangzhaode** [comment]
应该还是历史信息没有处理好，重新实现下历史信息的内容

**Comment by Moxoo** [comment]
> 应该还是历史信息没有处理好，重新实现下历史信息的内容

历史信息 这部分代码是指modeling_chatglm.py里的吗
