### ISSUE TITLE
VARP Llm::disk_embedding疑问

### ISSUE THREAD

**Issue by Moxoo** [wangzhaode/mnn-llm#129]
大佬，我看到llm.cpp里的disk_embedding函数可以省内存，但是每个模型的embeddings_bf16.bin是怎么获取的，我看到release里有qwen-1.8B的embeddings_bf16.bin，其他模型没有

**Comment by wangzhaode** [comment]
这个没有一一上传，export onnx的时候不分段，就会把embedding导出成一个二进制文件，改一下名字直接用就行了

**Comment by Moxoo** [comment]
哦哦好的，要加--embed_bf16选项吗

**Comment by wangzhaode** [comment]
> 哦哦好的，要加--embed_bf16选项吗

要加的 目前默认用bf16的，二进制文件会小一些；
如果不加的话是fp32的，disk_embedding的代码要稍微改一下；

**Comment by wangzhaode** [comment]
> 这个没有一一上传，export onnx的时候不分段，就会把embedding导出成一个二进制文件，改一下名字直接用就行了

这个会把onnx导出成一个模型，并把权重文件导出成多个二进制文件，一般模型的embedding对应的二进制文件名是: `embed_.weight`

**Comment by Moxoo** [comment]
多谢大佬解答
