### ISSUE TITLE
Kernel MNNGemmHybridInt4 will cause segmentation fault in ARM devices

### ISSUE THREAD

**Issue by Lqlsoftware** [wangzhaode/mnn-llm#131]
MNN version: 2.8.0

Using MNNGemmHybridInt4 (from ConvolutionHybrid, enable lowMemory) as the GEMM kernel will cause segmentation fault.

This situation occurs when I try to run **mnn-llm** with **Qwen-1.7B** and **ChatGLM3-6B** on M1 Pro and other android devices.

**Comment by wangzhaode** [comment]
M1 soc can't using register x16 - x18, this bug has fixed in https://github.com/alibaba/MNN/commit/1a5609b8617df2950d0f0187bf482945794b6a98

you can update MNN code and try it again

**Comment by Lqlsoftware** [comment]
Thx, this patch fixes the problem.
