### ISSUE TITLE
Android studio运行adb shell "cd /data/local/tmp && export LD_LIBRARY_PATH=. && ./cli_demo -m model"时报错如下

### ISSUE THREAD

**Issue by 0three** [wangzhaode/mnn-llm#132]
在运行adb shell "cd /data/local/tmp && export LD_LIBRARY_PATH=. && ./cli_demo -m model"时出现：
model path is -m
model type can't judge!
Segmentation fault 

如何解决呢？

**Comment by wangzhaode** [comment]
默认需要根据目录的名称来确定模型类型，否则就需要指定模型类型；你可以把model文件夹的名字修改为下载的relase名；你是用的是什么模型？

**Comment by 0three** [comment]
太感谢了，已解决
