### ISSUE TITLE
 qwen-1.8b-apk 使用时程序崩溃

### ISSUE THREAD

**Issue by MeetUo** [wangzhaode/mnn-llm#135]
模型可以正常加载，进入对话界面后输入一句话就会闪退到模型加载界面
手机总内存6G，可用内存3.2G
手机型号小米MIX2 处理器高通骁龙835

**Comment by wangzhaode** [comment]
- 3.2G内存是足够用的；
- 输入一句话之后会有回复吗？

**Comment by MeetUo** [comment]
没有回复，会稍微卡顿一下，然后闪退到模型加载的界面

**Comment by wangzhaode** [comment]
能使用logcat抓一下crash 堆栈吗

**Comment by henrybit2007** [comment]
A/libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7a3c6ced94 in tid 6560 (xxx), pid 6333 (xxx)
同样问题，用的是作业帮的平板
定位崩溃的代码位置是：

**Comment by darengking** [comment]
@henrybit2007 你好，这个问题你解决了吗？
