### ISSUE TITLE
Plans for android GPU suppport for qwen 1.8B

### ISSUE THREAD

**Issue by Nick-infinity** [wangzhaode/mnn-llm#136]
Hello @wangzhaode , what are the plans to add opencl support for android adreno gpu using opencl? Can you please provide some information

**Comment by wangzhaode** [comment]
In version 2.8.1 of MNN 2.8.1 has support for inference using OpenCL-based int4 quantized models has been added. However, the inference speed has not yet met expectations. 

We will complete performance optimization before the release of version 2.8.3.

**Comment by Nick-infinity** [comment]
> In version 2.8.1 of MNN, support for inference using OpenCL-based int4 quantized models has been added. However, the inference speed has not yet met expectations.
> 
> We will complete performance optimization before the release of version 2.8.3.

Thank you very much for reply. May I know if we can use it to test the models on our end? Can you share what tokens/s did we get with opencl? I would like to contribute to MNN-LLM project

**Comment by wangzhaode** [comment]
I will be conducting performance tests on OpenCL soon and will provide feedback in this issue.

**Comment by wangzhaode** [comment]
test on MNN 2.8.1 OpenCL, speed as below:
```
llama2-7b-int4 on MacbookPro Intel UHD 630:  //  SIMILAR TO llama.cpp
  mnn-llm: prefill speed = 6.33 tok/s, decode speed = 0.78 tok/s
  llama.cpp:  prefill speed = 1.26 tok/s, decode speed = 0.90 tok/s

qwen-1.8b-int4 on MacbookPro Intel UHD 630: 
 mnn-llm: prefill speed = 13.42 tok/s, decode speed = 1.59 tok/s

qwen-1.8b-int4 on Adreno 730 // TOO SLOW
  mnn-llm: prefill speed = 3.14 tok/s, decode speed = 0.29 tok/s
```
Now opencl decode speed is slow because shape mutable spend many time for MNN's `resize` function.  We will optimize the `resize` impl to speed up.

**Comment by Nick-infinity** [comment]
Thanks for the update @wangzhaode . Can you point me to int4 opencl kernels used in 2.8.1 so that I can give them a spin.
Also, do you dequantize the weights in the memory of kernel or do you first dequantize the weight and then use them in kernel for matmuls?
eg:
1. int4_weights -> MatMul Kernel (load chunk of weight and dequantize) -> output
2. int4_weights -> Dequantize to fp16 -> MatMul_fp16 -> output

**Comment by wangzhaode** [comment]
code: https://github.com/alibaba/MNN/blob/d284430f92557aa8b4cc435752b1dff3309f2e38/source/backend/opencl/execution/cl/gemm_buf.cl#L134

using 1th method, int4 weight dequntize in kernel.
