### ISSUE TITLE
能否发挥 NPUs of 天玑9300 或者 骁龙 8gen3? 

### ISSUE THREAD

**Issue by forhonourlx** [wangzhaode/mnn-llm#137]
大佬，现在能否发挥天玑9300 或者 骁龙 8gen3 的NPU啊？天玑9300号称能跑70B当真吗？

**Comment by wangzhaode** [comment]
移动端的NPU不开放算子级别的编程接口；我们没办法直接使用NPU （遗憾

**Comment by wangzhaode** [comment]
只能调用硬件厂商提供的框架

**Comment by forhonourlx** [comment]
感谢大佬。希望未来格局能发生改变~

**Comment by wangzhaode** [comment]
> 大佬，现在能否发挥天玑9300 或者 骁龙 8gen3 的NPU啊？天玑9300号称能跑70B当真吗？

70B 使用int4量化之后也得有30+G大小，首先内存大小是个问题，其次decode阶段内存带宽是问题 LPDDR5 按照bandwidth 45 GB/s 来计算；NPU算力再高在这个bandwidth下最多能达到1.5 tok/s， 速度也是比较差的。

**Comment by forhonourlx** [comment]
> > 大佬，现在能否发挥天玑9300 或者 骁龙 8gen3 的NPU啊？天玑9300号称能跑70B当真吗？
> 
> 70B 使用int4量化之后也得有30+G大小，首先内存大小是个问题，其次decode阶段内存带宽是问题 LPDDR5 按照bandwidth 45 GB/s 来计算；NPU算力再高在这个bandwidth下最多能达到1.5 tok/s， 速度也是比较差的。

原来如此。。怪不得Mediatek VIVO宣传完也没个动静。。。

**Comment by wangzhaode** [comment]
> > > 大佬，现在能否发挥天玑9300 或者 骁龙 8gen3 的NPU啊？天玑9300号称能跑70B当真吗？
> > 
> > 
> > 70B 使用int4量化之后也得有30+G大小，首先内存大小是个问题，其次decode阶段内存带宽是问题 LPDDR5 按照bandwidth 45 GB/s 来计算；NPU算力再高在这个bandwidth下最多能达到1.5 tok/s， 速度也是比较差的。
> 
> 原来如此。。怪不得Mediatek VIVO宣传完也没个动静。。。

如果利用稀疏性可能会有提升，但是感觉移动端跑70B目前看还是比较难的；
目前主要是内存带宽问题；算力的话使用支持SME（因为支持的设备不多，MNN目前还没支持）的CPU其实是足够用的；
