### ISSUE TITLE
HELP! 安卓端版mnn-llm.apk加载chatglm3-6b-mnn无法操作

### ISSUE THREAD

**Issue by forhonourlx** [wangzhaode/mnn-llm#138]
大佬，
安卓端版mnn-llm.apk加载chatglm3-6b-mnn无法操作，按照[https://github.com/wangzhaode/mnn-llm/releases/tag/mnn-llm-apk](url) adb传入模型后，“选择模型文件夹”有目录选项，但点击“加载模型”后，显示的还是24.56M的block块下载，如图请问如何处理啊？
![Screenshot_20240105_134307](https://github.com/wangzhaode/mnn-llm/assets/16576219/a209c331-0bf9-4444-aabe-1e6ca1b0a649)
![Screenshot_20240105_134325](https://github.com/wangzhaode/mnn-llm/assets/16576219/adab25cc-fcd8-4db3-ac3f-220ef4d406d2)

by VIVO X100 PRO

提前谢过！

**Comment by wangzhaode** [comment]
请问你有没有按照提示把模型文件放置到指定位置呢

**Comment by forhonourlx** [comment]
我使用了如下adb命令：
```
adb shell mkdir /data/local/tmp/mnn-llm
adb push ./chatglm3-6b-mnn  /data/local/tmp/mnn-llm
adb push ./baichuan2-7b-chat-mnn  /data/local/tmp/mnn-llm
adb push ./codegeex2-6b-mnn  /data/local/tmp/mnn-llm
```

然后刚才我又重新运行了一遍，得到如下返回：
```
(base) PS D:\LLM\mnn-llm> adb shell mkdir /data/local/tmp/mnn-llm
* daemon not running; starting now at tcp:5037
* daemon started successfully
mkdir: '/data/local/tmp/mnn-llm': File exists
(base) PS D:\LLM\mnn-llm> adb push ./chatglm3-6b-mnn  /data/local/tmp/mnn-llm
./chatglm3-6b-mnn\: 31 files pushed, 0 skipped. 47.0 MB/s (3537967643 bytes in 71.720s)
```
比如选择chatglm3-6b-mnn模型后，点加载模型，然后就到了可能是qwen-1.8b-mnn的下载页面（每个分块24.56M），没有加载模型。。。

**Comment by wangzhaode** [comment]
我看了下是模型检测的问题，我写的例子打开了DISK_EMBEDDING需要`embeddings_bf16.bin` 文件

**Comment by forhonourlx** [comment]
恳请大佬修复~感恩！
