### ISSUE TITLE
qwen-1.8 转换的mnn和官网提供的mnn block文件大小不一样，我转的mnn最终是39m  官方的是24.6M

### ISSUE THREAD

**Issue by moyu505** [wangzhaode/mnn-llm#139]
你好，
我用 https://github.com/wangzhaode/llm-export/releases/tag/qwen-1.8b-onnx  转换mnn
但是 mnn 和 官网提供的大小不一样  https://github.com/wangzhaode/mnn-llm/releases/tag/qwen-1.8b-mnn

我用自己转换的跑，会内存溢出

转换命令：
mnnconvert -f ONNX --modelFile block_0.onnx --MNNModel block_0.mnn --weightQuantBits 4 --bizCode biz

llm-export 版本是最新的（20240105的master）
mnn的版本是2.8.0

![image](https://github.com/wangzhaode/mnn-llm/assets/5894969/b3456c67-a89d-444e-b29a-9eda9b23434e)

**Comment by wangzhaode** [comment]
mnn请更新到2.8.1， 2.8.0转换时有个小bug

**Comment by moyu505** [comment]
> mnn请更新到2.8.1， 2.8.0转换时有个小bug

好的，谢谢，我去试试，我自己转换的时候还会缺少一个embeddings_bf16.bin文件，这个文件是通过什么参数控制生成？

**Comment by moyu505** [comment]
> embeddings_bf16.bin



> mnn请更新到2.8.1， 2.8.0转换时有个小bug



> mnn请更新到2.8.1， 2.8.0转换时有个小bug
使用2.8.1生成可以对齐，但是缺少了embeddings_bf16.bin这个文件，我把官方的embeddings_bf16.bin的这个文件拷贝过去，可以成功运行
