### ISSUE TITLE
[Question]: Add support for tinyllama 1.1 B model

### ISSUE THREAD

**Issue by Nick-infinity** [wangzhaode/mnn-llm#140]
Hello, I have added support for llm-export repo to convert tinyllama 1.1B model and then made changes to model template in mnn-llm to load it correct. This model crashes at runtime in mnn. It would be good If I @wangzhaode can guide me with whats fundamentally required to add new model support with hidden dim size 2048. Is only a hidden dim size of 4096 supported as of now?

**Comment by wangzhaode** [comment]
You can inherit from the Llama2_7b class and modify the hidden_size_, layer_nums_, and key_value_shape_ attributes.

**Comment by Nick-infinity** [comment]
> You can inherit from the Llama2_7b class and modify the hidden_size_, layer_nums_, and key_value_shape_ attributes.

Yes, I tried doing the same . In the llm-export I set the  self.past_kv_shape = [22, 2, 1, 32, 0, 64] and in Mnn-llm tried setting  key_value_shape_ = {2, 1, 32, 0, 64}; in inherited llama2_7B class. Modified the hidden size and num layers etc.

1. Can you tell me what does each index represent in  self.past_kv_shape = [22, 2, 1, 32, 0, 64] & key_value_shape_ = {2, 1, 32, 0, 64} in llm-export ? I have some idea as I modified it as per tinyllama 1.1B. but it would be good to know from you.
2. Does mnn support Grouped query attention as of now? As TinyLLama uses Grouped query attention

**Comment by Nick-infinity** [comment]
@wangzhaode Finally I am able to run this model. Now I Need to check the correctness of this model wrt accuracy

**Comment by Nick-infinity** [comment]
This apk : https://github.com/wangzhaode/mnn-llm/releases/tag/qwen-1.8b-apk is very fast as compared to any of the apk that I build from source or using android cli. In my understanding the backend MNN is packed as native .so in all the cases.
I can not understand how very big performance difference is there in soruce built apk/cli vs the one published under assets.

Can you please help me @wangzhaode
