### ISSUE TITLE
自己编译的apk运行速度很慢

### ISSUE THREAD

**Issue by litao1991** [wangzhaode/mnn-llm#147]
大佬，请教个问题，windows平台编译apk，使用master以及2.8.1的MNN编译的APK加载模型慢，每个token的生成时间都有着明显比你提供的apk慢，请问你知道是什么原因吗？

**Comment by wangzhaode** [comment]
编译MNN时有没有打开这个宏：`MNN_LOW_MEMORY `

**Comment by litao1991** [comment]
> 编译MNN时有没有打开这个宏：`MNN_LOW_MEMORY `

打开这个宏之后速度正常，多谢

**Comment by moyu505** [comment]
解决了？我也遇到相同问题，
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=ON \
-DMNN_LOW_MEMORY=ON \
-DMNN_BUILD_TEST=ON \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

速度还是很慢，请问有啥参数需要修改
