### ISSUE TITLE
有什么途径可提高输出质量？(Phi2 参考)

### ISSUE THREAD

**Issue by kmn1024** [wangzhaode/mnn-llm#150]
MNN 的输出和 [Sample Code](https://huggingface.co/microsoft/phi-2#sample-code) 比起来，有区别. Prompt 是 "Einstein said"

Sample code:
> 'Einstein said that the universe is like a giant machine, and that everything in it is connected. He believed that the universe was made up of tiny particles called atoms, which were constantly moving and interacting with each other.\n\nEinstein\'s theory of relativity also helped us understand how gravity works. He believed that gravity was not a force, but rather a cuin the fabric of space-time. This means that objects with mass create a "dent" in space-time, which causes other objects to move towards them.\n\nEinstein\'s work has had a huge impact on our understanding of the universe. His theories'

Phi2 (下载的参数):
> , the most important thing is to "do the right thing" and that the most important thing is to "do the right thing" and to "do the right thing" and to "do the right thing" and to "do the right thing" and to "do the^C

Phi2 自己编 8-bit:
> , "God does not play dice with the universe."
The universe is a complex system. It is not a random process.
The universe is a complex system. It is not a random process. It is a complex system. It is a complex system. It is a complex^C

8-bit 明显比 4-bit 好, 但还是比不上 Sample Code 的质量。

**Comment by kmn1024** [comment]
譬如说，我先跑 AutoGPTQ 制造一个 checkpoint，之后能 convert 成 MNN 吗 （不需要再quant)。

**Comment by Nick-infinity** [comment]
I dont think GPTQ is supported on MNN. Every New Quantization needs its own Dequantize Kernel or logic to dequantize weights in the Operator kernels.

**Comment by wangzhaode** [comment]
> 譬如说，我先跑 AutoGPTQ 制造一个 checkpoint，之后能 convert 成 MNN 吗 （不需要再quant)。

- 如 @Nick-infinity 所说，目前确实还不支持GPTQ格式的量化；这个需要增加kernel的实现。我们在考虑这个问题了，之后会支持多种量化方式。
- 目前来看增加精度的一些方法如下：
     - 使用int8非对称量化转换模型；
     - 在模型运行时将precision从`Precision_Low`修改为`Precision_Normal`

**Comment by kmn1024** [comment]
谢各位大佬！
