### ISSUE TITLE
Please upgrade your GNU compiler to one that supports __declspec

### ISSUE THREAD

**Issue by do-one-thing-to-well** [wangzhaode/mnn-llm#152]
我在**Windows11**环境下的**Android Studio**中运行项目，报该错误，以下是详细信息：
`In file included from D:/WorkSpace/AndroidWorkSpace/AI/mnn-llm-qwen-1.8b-apk/android/app/src/main/jni/llm_mnn_jni.cpp:6:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\string:504:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\string_view:175:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\__string:57:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\algorithm:643:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\memory:673:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\atomic:550:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\__threading_support:27:
D:/WorkSpace/AndroidWorkSpace/AI/mnn-llm-qwen-1.8b-apk/android/app/src/main/jni/../../../../../include\pthread.h:320:8: error: redefinition of 'timespec'
D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\linux/time.h:25:8: note: previous definition is here
In file included from D:/WorkSpace/AndroidWorkSpace/AI/mnn-llm-qwen-1.8b-apk/android/app/src/main/jni/llm_mnn_jni.cpp:6:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\string:504:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\string_view:175:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\__string:57:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\algorithm:643:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\memory:673:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\atomic:550:
In file included from D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\__threading_support:27:
D:/WorkSpace/AndroidWorkSpace/AI/mnn-llm-qwen-1.8b-apk/android/app/src/main/jni/../../../../../include\pthread.h:541:3: error: Please upgrade your GNU compiler to one that supports __declspec.
D:/WorkSpace/AndroidWorkSpace/AI/mnn-llm-qwen-1.8b-apk/android/app/src/main/jni/../../../../../include\pthread.h:585:24: error: typedef redefinition with different types ('ptw32_handle_t' vs 'long')
D:/sdk/android/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\bits/pthread_types.h:104:14: note: previous definition is here`

> 我用的是华为的笔记本，看错误提示好像是因为我笔记本GPU不支持`__declspec`，
我试着按照网上给的处理方式：
1. 修改了`include`目录下的`httplib.h`中头部引入方式，发现不起作用。
2. 修改了`pthred.h`头部引入`sched.h`的位置的代码，发现仍报错。

我对C/C++不懂，请问我该怎么解决这个问题？感谢

**Comment by do-one-thing-to-well** [comment]
我又重新看了该项目的README文件，里面在**本地编译**和**执行**两个标题内容下，分别罗列了在windows上执行的命令和android上执行的命令，疑惑的是，windows上的命令执行可以使用Windows Terminal或PowerShell 来执行命令，但是android的那个命令又该如何执行呢？

**Comment by wangzhaode** [comment]
apk安装之后不需要使用adb命令，README中的adb命令是针对android命令行编译的测试用的

**Comment by do-one-thing-to-well** [comment]
仍然报错，我说下我的步骤：

1. 先拉取`Qwen-1_8B-Chat-int8`
2. 在**PowerShell**中执行 **本地编译的命令：./script/build.ps1**，这一步会clone MNN的代码，然后会自动在include目录生成httplib.h、pthread.h、sched.h 三个文件，三个文件按照你上面说的，我全都删了，因为会报错 
3. 使用AndroidStudio打开项目中android目录，然后编译，我NDK路径都指定了，然后编译之后报错：

**Comment by do-one-thing-to-well** [comment]
`
Caused by: Build command failed.
Error while executing process D:\sdk\android\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\WorkSpace\AndroidWorkSpace\AI\release\mnn-llm\android\app\.cxx\cmake\debug\armeabi-v7a llm_mnn}
ninja: Entering directory `D:\WorkSpace\AndroidWorkSpace\AI\release\mnn-llm\android\app\.cxx\cmake\debug\armeabi-v7a'
[1/4] Building CXX object CMakeFiles/llm_mnn.dir/llm_mnn_jni.cpp.o
[2/4] Building CXX object CMakeFiles/llm_mnn.dir/D_/WorkSpace/AndroidWorkSpace/AI/release/mnn-llm/src/tokenizer.cpp.o
[3/4] Building CXX object CMakeFiles/llm_mnn.dir/D_/WorkSpace/AndroidWorkSpace/AI/release/mnn-llm/src/llm.cpp.o
[4/4] Linking CXX shared library D:\WorkSpace\AndroidWorkSpace\AI\release\mnn-llm\android\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libllm_mnn.so
FAILED: D:/WorkSpace/AndroidWorkSpace/AI/release/mnn-llm/android/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libllm_mnn.so 
cmd.exe /C "cd . && D:\sdk\android\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi21 --sysroot=D:/sdk/android/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--gc-sections -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libllm_mnn.so -o D:\WorkSpace\AndroidWorkSpace\AI\release\mnn-llm\android\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libllm_mnn.so CMakeFiles/llm_mnn.dir/llm_mnn_jni.cpp.o CMakeFiles/llm_mnn.dir/D_/WorkSpace/AndroidWorkSpace/AI/release/mnn-llm/src/llm.cpp.o CMakeFiles/llm_mnn.dir/D_/WorkSpace/AndroidWorkSpace/AI/release/mnn-llm/src/tokenizer.cpp.o -LD:/WorkSpace/AndroidWorkSpace/AI/release/mnn-llm/android/app/src/main/jni/libs/arm64-v8a -lMNN -lMNN_Express -llog -latomic -lm && cd ."
ld: error: unable to find library -lMNN
ld: error: unable to find library -lMNN_Express
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
`

**Comment by wangzhaode** [comment]
Android apk的话不需要执行`./script/build.ps1`，这个是编译windows上的可执行程序用的脚本；
Android apk编译流程：
1. 首先编译MNN的android so库；
2. 然后将`libMNN.so`和`libMNN_Express.so`放置在目录`android/app/src/main/jni/libs/arm64-v8a`下；
3. 使用AndroidStudio编译；

我回头整理个README放里面吧

**Comment by do-one-thing-to-well** [comment]
感谢，按照你说的方式我已经编译过了，

**Comment by do-one-thing-to-well** [comment]
感谢，按照你说的方式，我已经编译过了，如图：
![微信截图_20240125130119](https://github.com/wangzhaode/mnn-llm/assets/22162731/4ab4709f-a22b-4ad4-80e9-e1e74551473a)
现在有几个问题：
1. 手机端下载不动，是需要用梯子么？
2. 我不知道我下载的是哪个模型，我该怎么判断？
3. 我想手机集成[Qwen-1_8B-Chat-Int8](https://www.modelscope.cn/models/qwen/Qwen-1_8B-Chat/summary)和[Qwen-1_8B-Chat-Int4]这两个模型（因为我是编译的MNN的库），该怎么做？

**Comment by do-one-thing-to-well** [comment]
用梯子下载，但是都为**0M**
![微信截图_20240125133757](https://github.com/wangzhaode/mnn-llm/assets/22162731/74c341b7-56eb-4c4f-9c11-7c0a93825308)

**Comment by wangzhaode** [comment]
不用下载的 你可以把下载好的模型打包到apk中，或者把模型`adb push /data/local/tmp/mnn-llm/`

**Comment by do-one-thing-to-well** [comment]
还是有问题的，大佬，adb push 模型之后，
![微信截图_20240125154713](https://github.com/wangzhaode/mnn-llm/assets/22162731/6f6c22dc-da5e-4f3a-93bf-3bce6cea32a4)
点击模型，然后加载模型，进不到聊天页面。。
我看了其他Issue中有提到这个问题，应该是同一个问题，恳请大佬修复，，
