### ISSUE TITLE
为什么同样是4bit量化模型，mnn-llm会比llama.cpp快几倍呢？

### ISSUE THREAD

**Issue by 22dimensions** [wangzhaode/mnn-llm#153]
![image](https://github.com/wangzhaode/mnn-llm/assets/33222038/d9761aa4-0dce-4500-90aa-633d836c6cbe)
技术方面有哪些不一样的地方

**Comment by wangzhaode** [comment]
- 支持`i8mm`指令，理论算力是`sdot`的2倍；
- 支持fp16/int4混合精度运算；
- 数据重拍方式不同，对reduce dim和output dim都做了pack；这个对prefill的性能提升比较大；

具体可以看下zhihu的文章介绍和代码实现。
