### ISSUE TITLE
求大佬修复这个DISK_EMBEDDING需要`embeddings_bf16.bin` 文件问题！

### ISSUE THREAD

**Issue by do-one-thing-to-well** [wangzhaode/mnn-llm#154]
现在有一个问题，没法进入聊天页面：
      
        我看了下是模型检测的问题，我写的例子打开了DISK_EMBEDDING需要`embeddings_bf16.bin` 文件

_Originally posted by @wangzhaode in https://github.com/wangzhaode/mnn-llm/issues/138#issuecomment-1880284527_

**Comment by wangzhaode** [comment]
不好记意思 最近比较忙没来得及上传，您需要哪一个 我优先上传

**Comment by wangzhaode** [comment]
qwen相关模型均已上传

**Comment by do-one-thing-to-well** [comment]
感谢大佬。[抱拳]
