### ISSUE TITLE
下载完qwen-1.8b-mnn-int8，加载完还是无法到聊天页面

### ISSUE THREAD

**Issue by do-one-thing-to-well** [wangzhaode/mnn-llm#156]
https://github.com/wangzhaode/mnn-llm/issues/138
同这个问题，如果使用qwen-1.8b模型里面的embeddings_bf16.bin文件是否可以？

_Originally posted by @ZW-BOY1126 in https://github.com/wangzhaode/mnn-llm/issues/143#issuecomment-1884584223_
            
我重新下载了qwen-1.8b-mnn-int8模型，然后也重新编译了项目，手机端选择模型之后到下载页面，还是无法进入聊天页面

**Comment by wangzhaode** [comment]
打开APP之后是什么界面

**Comment by do-one-thing-to-well** [comment]
1. 选择好模型之后，点击`加载模型`，然后跳转至`下载页`:

![微信截图_20240130160923](https://github.com/wangzhaode/mnn-llm/assets/22162731/db4c7d75-2828-4ec0-82d2-4de232c8a32b)

2. 然后`关闭下载页`，返回首页，如下图：

![微信截图_20240130160736](https://github.com/wangzhaode/mnn-llm/assets/22162731/81fc87f0-9e16-4181-bba6-567d6112609c)

**Comment by wangzhaode** [comment]
我看一下
