### ISSUE TITLE
Segmentation Fault in PC Linux

### ISSUE THREAD

**Issue by iamfaith** [wangzhaode/mnn-llm#158]
model path is ../resource/models/chatglm2-6b
### model name : Chatglm2_6b
The device support i8sdot:0, support fp16:0, support i8mm: 0
[New Thread 0x7ffff7461700 (LWP 41669)]
[New Thread 0x7ffff6c60700 (LWP 41670)]
[New Thread 0x7ffff645f700 (LWP 41671)]
load tokenizer
load tokenizer Done
[ 10% ] load ../resource/models/chatglm2-6b/lm.mnn model ... Done!
[ 13% ] load ../resource/models/chatglm2-6b/embedding.mnn model ...
Thread 1 "cli_demo" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:436
436     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.

**Comment by wangzhaode** [comment]
Please paste the stack of this error
