### ISSUE TITLE
Error for concat size of op [ /block/self_attn/Concat_5_output_0 ], the 1 input not match output

### ISSUE THREAD

**Issue by yangyangsu29** [wangzhaode/mnn-llm#168]
download the Officially provided qwen-1.8b-int4 model，run the ./cli_demo, error as follows:
![WechatIMG124](https://github.com/wangzhaode/mnn-llm/assets/23189201/0d8be1a4-6d71-4e85-870f-2a5ba565f088)

**Comment by DataXujing** [comment]
遇到了相同的问题

**Comment by Nick-infinity** [comment]
Is there any fix for this issue? I am facing the same issue @wangzhaode @yangyangsu29
