### ISSUE TITLE
Error: No encoding found for the sequence starting at position 0

### ISSUE THREAD

**Issue by OliverQueen1466** [wangzhaode/mnn-llm#169]
Broad cast error, dim1 = 9, dim2 = 36
Compute Shape Error for /block/self_attn/Mul_output_0
code=3 in onForward, 372 
Segmentation fault
使用cli编译后，对话窗口可以正常打开，但是输入prompt后无法输出回答。报这个错误

**Comment by wangzhaode** [comment]
检查一下 `tokenizer.txt` 的路径是否正确

**Comment by OliverQueen1466** [comment]
![Screenshot_20240318_145817](https://github.com/wangzhaode/mnn-llm/assets/99124505/b9fa3bc3-3bb2-45b7-8fc5-8dbbc07ef62d)
tokenizer.txt 放在了mnn模型的里面

**Comment by wangzhaode** [comment]
能贴一下执行之后的log吗 可能是目录名称导致模型类型判断错了

**Comment by Nick-infinity** [comment]
Did you Use --skip_slim option while exporting the model? If not then please use this option in llm_export

**Comment by OliverQueen1466** [comment]
改了目录就可以工作了，感谢
