### ISSUE TITLE
请问mnn-llm现在是否支持opencl后端？能否调用GPU？如果希望利用安卓设备的GPU进行推理需要做哪些更改？

### ISSUE THREAD

**Issue by qtyandhasee** [wangzhaode/mnn-llm#170]
编译MNN主库时开启OpenCL（MNN_OPENCL=ON），但是测试时GPU并没有被调用（GPU利用率为0%）
在linux平台使用NDK编译，部署在安卓上

**Comment by qtyandhasee** [comment]
![Uploading 0ef68e4c-8179-441a-8fe3-c9bf2a185dbc.png…]()

**Comment by Nick-infinity** [comment]
Link libllm.so against libMNN_OpenCL.so and pass Opencl as backend config in llm.cpp

**Comment by qtyandhasee** [comment]
@Nick-infinity 


> Link libllm.so against libMNN_OpenCL.so and pass Opencl as backend config in llm.cpp

Thank you! This works for me

**Comment by tzhang2014** [comment]
@qtyandhasee 请问你跑的是多大规模的模型，我用opencl跑Qwen1.8b，报输入大小参数有问题，

**Comment by qtyandhasee** [comment]
> @qtyandhasee 请问你跑的是多大规模的模型，我用opencl跑Qwen1.8b，报输入大小参数有问题，

@tzhang2014 我跑qwen-1.8b模型基本可以正常运行，提问三四次后会出现CL报错，建议使用MNN最新的版本（2.8.3），qwen1.5-0.5b也可以运行，也会出现”慢慢的“报错，并且使用GPU的推理速度比使用CPU的慢多了，，，

**Comment by yinwangsong** [comment]
现在gpu效果怎么样啊？可以跑了吗
