### ISSUE TITLE
英伟达T4上使用opencl报错

### ISSUE THREAD

**Issue by tzhang2014** [wangzhaode/mnn-llm#172]
1. MNN版本 2.8.1
    MNN编译命令 
    cmake .. \
    -DMNN_BUILD_TEST=ON \
    -DMNN_OPENCL=ON \
    -DMNN_BUILD_QUANTOOLS=ON \
    -DMNN_BUILD_DEMO=ON \
    -DMNN_BUILD_CONVERTER=ON \
    -DMNN_BUILD_BENCHMARK=ON \
    -DMNN_BUILD_OPENCV=ON \
    -DMNN_IMGCODECS=ON \
    -DMNN_SEP_BUILD=OFF
    make -j32 

2. mnn-lmm版本大概是2024年1月15号之前的最近版本
3. 模型版本 qwen-1.8b-int4
sh run.sh 
model path is ../../llm-export-master/qwen-1.8b-mnn
### model name : Qwen_1.8b
The device support i8sdot:0, support fp16:0, support i8mm: 0
load tokenizer
load tokenizer Done
[ 10% ] load ../../llm-export-master/qwen-1.8b-mnn/lm.mnn model ... Done!
[ 13% ] load ../../llm-export-master/qwen-1.8b-mnn/embedding.mnn model ... Alloc Image 512 x 151936 error, code:-40 
onCopyBuffer float error !!! 
Done!
[ 20% ] load ../../llm-export-master/qwen-1.8b-mnn/block_0.mnn model ... Done!
[ 24% ] load ../../llm-export-master/qwen-1.8b-mnn/block_1.mnn model ... Done!
[ 27% ] load ../../llm-export-master/qwen-1.8b-mnn/block_2.mnn model ... Done!
[ 31% ] load ../../llm-export-master/qwen-1.8b-mnn/block_3.mnn model ... Done!
[ 34% ] load ../../llm-export-master/qwen-1.8b-mnn/block_4.mnn model ... Done!
[ 38% ] load ../../llm-export-master/qwen-1.8b-mnn/block_5.mnn model ... Done!
[ 41% ] load ../../llm-export-master/qwen-1.8b-mnn/block_6.mnn model ... Done!
[ 45% ] load ../../llm-export-master/qwen-1.8b-mnn/block_7.mnn model ... Done!
[ 48% ] load ../../llm-export-master/qwen-1.8b-mnn/block_8.mnn model ... Done!
[ 52% ] load ../../llm-export-master/qwen-1.8b-mnn/block_9.mnn model ... Done!
[ 55% ] load ../../llm-export-master/qwen-1.8b-mnn/block_10.mnn model ... Done!
[ 58% ] load ../../llm-export-master/qwen-1.8b-mnn/block_11.mnn model ... Done!
[ 62% ] load ../../llm-export-master/qwen-1.8b-mnn/block_12.mnn model ... Done!
[ 65% ] load ../../llm-export-master/qwen-1.8b-mnn/block_13.mnn model ... Done!
[ 69% ] load ../../llm-export-master/qwen-1.8b-mnn/block_14.mnn model ... Done!
[ 72% ] load ../../llm-export-master/qwen-1.8b-mnn/block_15.mnn model ... Done!
[ 76% ] load ../../llm-export-master/qwen-1.8b-mnn/block_16.mnn model ... Done!
[ 79% ] load ../../llm-export-master/qwen-1.8b-mnn/block_17.mnn model ... Done!
[ 83% ] load ../../llm-export-master/qwen-1.8b-mnn/block_18.mnn model ... Done!
[ 86% ] load ../../llm-export-master/qwen-1.8b-mnn/block_19.mnn model ... Done!
[ 90% ] load ../../llm-export-master/qwen-1.8b-mnn/block_20.mnn model ... Done!
[ 93% ] load ../../llm-export-master/qwen-1.8b-mnn/block_21.mnn model ... Done!
[ 97% ] load ../../llm-export-master/qwen-1.8b-mnn/block_22.mnn model ... Done!
[100% ] load ../../llm-export-master/qwen-1.8b-mnn/block_23.mnn model ... Done!
prompt file is prompt.txt
### warmup ... onCopyBuffer float error !!! 
Done
onCopyBuffer float error !!! 
1 warning generated.
慢慢的onCopyBuffer float error !!! 
慢慢的onCopyBuffer float error !!!

**Comment by wangzhaode** [comment]
使用OpenCL的buffer模式运行看一下

**Comment by tzhang2014** [comment]
##更新到MNN2.8.3，改成buffer后输出的结果是不正常的
### model name : Qwen_1.8b
mode is 68
The device support i8sdot:0, support fp16:0, support i8mm: 0
load tokenizer
load tokenizer Done
### disk embedding is 0
[ 10% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/lm.mnn model ... Done!
[ 13% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/embedding.mnn model ... Done!
[ 20% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_0.mnn model ... Done!
[ 24% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_1.mnn model ... Done!
[ 27% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_2.mnn model ... Done!
[ 31% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_3.mnn model ... Done!
[ 34% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_4.mnn model ... Done!
[ 38% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_5.mnn model ... Done!
[ 41% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_6.mnn model ... Done!
[ 45% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_7.mnn model ... Done!
[ 48% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_8.mnn model ... Done!
[ 52% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_9.mnn model ... Done!
[ 55% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_10.mnn model ... Done!
[ 58% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_11.mnn model ... Done!
[ 62% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_12.mnn model ... Done!
[ 65% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_13.mnn model ... Done!
[ 69% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_14.mnn model ... Done!
[ 72% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_15.mnn model ... Done!
[ 76% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_16.mnn model ... Done!
[ 79% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_17.mnn model ... Done!
[ 83% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_18.mnn model ... Done!
[ 86% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_19.mnn model ... Done!
[ 90% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_20.mnn model ... Done!
[ 93% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_21.mnn model ... Done!
[ 97% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_22.mnn model ... Done!
[100% ] load /data/tianzhang3/LLM/EdgeLLM/llm-export-master/qwen-1.8b-mnn/block_23.mnn model ... Done!
prompt file is prompt.txt
### warmup ... 
Done
1 warning generated.
1 warning generated.
慢慢的
慢慢的
