### ISSUE TITLE
Support for Lora adapter layers for LLM inference

### ISSUE THREAD

**Issue by TejasRavichandran1995** [wangzhaode/mnn-llm#181]
the llm-export utility [https://github.com/wangzhaode/llm-export](url) seems to have support to directly export a lora.mnn file during conversion in the llm_export.py .

However , it seems to me the framework does not yet support inference with lora.mnn exported file. 
Any pointers regarding this would be useful :).
@wangzhaode

**Comment by wangzhaode** [comment]
MNN-2.9.0 will support apply lora on device.

**Comment by TejasRavichandran1995** [comment]
Sure. Thanks @wangzhaode .
Any planned rough timelines on the 2.9.0 release?
