### ISSUE TITLE
Missing a file for the llama3-8b-instruct-mnn model

### ISSUE THREAD

**Issue by ghost** [wangzhaode/mnn-llm#183]
Hello, I think one file is missing for the llama3-8b-instruct-mnn model
![screen](https://github.com/wangzhaode/mnn-llm/assets/30768306/6f68d757-3708-4d2c-b150-a684604d66d1)

**Comment by wangzhaode** [comment]
not missing file, just process info has some inaccurate

**Comment by IgorZorkov** [comment]
OK, clear.
Why does the model always answer every question the same way?


> Q: who is the best football player in the world?
> 
> _**A: It seems like you started to ask a question, but didn't complete it.**_
> 
> _**If you could finish your question, I'd be happy to help you out!**_
