### ISSUE TITLE
A: libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found [1]    58628 abort      ./cli_demo ../qwen1.5-0.5b-chat

### ISSUE THREAD

**Issue by CoderXXLee** [wangzhaode/mnn-llm#186]
A: libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found
[1]    58628 abort      ./cli_demo ../qwen1.5-0.5b-chat

**Comment by wangzhaode** [comment]
请看下tokenizer.txt文件路径是否正确

**Comment by CoderXXLee** [comment]
问题已解决，谢谢

**Comment by CoderXXLee** [comment]
> 请看下tokenizer.txt文件路径是否正确



> 请看下tokenizer.txt文件路径是否正确

问题已解决，谢谢
