### ISSUE TITLE
llama2-7b回复错误与重复

### ISSUE THREAD

**Issue by QIANXUNZDL123** [wangzhaode/mnn-llm#192]
您好，我编译了该工程并下载了llama2-7b-mnn  但是在使用的使用出现以下问题，
![image](https://github.com/wangzhaode/mnn-llm/assets/46549527/3762b10a-c025-413b-b434-0added96007d)

错误的回复，与重复的自我回复，请问这是什么原因，使用的命令是。 ./build/cli_demo ./llama2-7b-chat

**Comment by GrantLau1226** [comment]
I think it's that we're not asking questions in the right way，because the model is on the end side and offline.

**Comment by QIANXUNZDL123** [comment]
> I think it's that we're not asking questions in the right way，because the model is on the end side and offline.

no,i also asking some other questions, eg What is the longest river in the world? so what is the reason for this?
![image](https://github.com/wangzhaode/mnn-llm/assets/46549527/62386f20-bdcd-4f37-987d-b593665c7a6e)

**Comment by QIANXUNZDL123** [comment]
> > I think it's that we're not asking questions in the right way，because the model is on the end side and offline.
> 
> no,i also asking some other questions, eg What is the longest river in the world? so what is the reason for this? ![image](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)

**Comment by GrantLau1226** [comment]
As a matter of fact, I am experiencing the same situation. For this reason I deployed llama3 on PC for comparison. On PC, llama3 works significantly better, so I'm wondering if there could be a problem with the model in mnn format?

**Comment by GrantLau1226** [comment]
> > > I think it's that we're not asking questions in the right way，because the model is on the end side and offline.
> > 
> > 
> > no,i also asking some other questions, eg What is the longest river in the world? so what is the reason for this? ![image](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)

As a matter of fact, I am experiencing the same situation. For this reason I deployed llama3 on PC for comparison. On PC, llama3 works significantly better, so I'm wondering if there could be a problem with the model in mnn format?

**Comment by QIANXUNZDL123** [comment]
> > > > I think it's that we're not asking questions in the right way，because the model is on the end side and offline.
> > > 
> > > 
> > > no,i also asking some other questions, eg What is the longest river in the world? so what is the reason for this? ![image](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)
> 
> As a matter of fact, I am experiencing the same situation. For this reason I deployed llama3 on PC for comparison. On PC, llama3 works significantly better, so I'm wondering if there could be a problem with the model in mnn format?

I downloaded the model from the link provided by the author，  Model download path: https://github.com/wangzhaode/mnn-llm/releases     I'm not quite sure if it's a model format issue, I'm ready to try following the steps to convert onnx to mnn

**Comment by GrantLau1226** [comment]
> > > > > I think it's that we're not asking questions in the right way，because the model is on the end side and offline.
> > > > 
> > > > 
> > > > no,i also asking some other questions, eg What is the longest river in the world? so what is the reason for this? ![image](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)
> > 
> > 
> > As a matter of fact, I am experiencing the same situation. For this reason I deployed llama3 on PC for comparison. On PC, llama3 works significantly better, so I'm wondering if there could be a problem with the model in mnn format?
> 
> I downloaded the model from the link provided by the author， Model download path: https://github.com/wangzhaode/mnn-llm/releases I'm not quite sure if it's a model format issue, I'm ready to try following the steps to convert onnx to mnn

That's what I'm doing at the moment and can only find the problem by elimination .

**Comment by QIANXUNZDL123** [comment]
> > > > > > 我认为这是因为我们没有以正确的方式提出问题，因为模型处于端端和离线状态。
> > > > > 
> > > > > 
> > > > > 不，我还问了一些其他问题，例如世界上最长的河流是什么？那么这是什么原因呢？![图像](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)
> > > 
> > > 
> > > 事实上，我正在经历同样的情况。出于这个原因，我在 PC 上部署了 llama3 进行比较。在 PC 上，llama3 的效果要好得多，所以我想知道 mnn 格式的模型是否存在问题？
> > 
> > 
> > 我从作者提供的链接下载了模型，模型下载路径： https://github.com/wangzhaode/mnn-llm/releases 我不太确定这是否是模型格式问题，我准备尝试按照步骤将 onnx 转换为 mnn
> 
> 这就是我目前正在做的事情，只能通过消除来找到问题。

Can you let me know if you have any new progress or solve the problem？thanks

**Comment by GrantLau1226** [comment]
> > > > > > > 我认为这是因为我们没有以正确的方式提出问题，因为模型处于端端和离线状态。
> > > > > > 
> > > > > > 
> > > > > > 不，我还问了一些其他问题，例如世界上最长的河流是什么？那么这是什么原因呢？![图像](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)
> > > > 
> > > > 
> > > > 事实上，我正在经历同样的情况。出于这个原因，我在 PC 上部署了 llama3 进行比较。在 PC 上，llama3 的效果要好得多，所以我想知道 mnn 格式的模型是否存在问题？
> > > 
> > > 
> > > 我从作者提供的链接下载了模型，模型下载路径： https://github.com/wangzhaode/mnn-llm/releases 我不太确定这是否是模型格式问题，我准备尝试按照步骤将 onnx 转换为 mnn
> > 
> > 
> > 这就是我目前正在做的事情，只能通过消除来找到问题。
> 
> Can you let me know if you have any new progress or solve the problem？thanks

Sorry, I don't have a solution for this at the moment......

**Comment by QIANXUNZDL123** [comment]
> > > > > > > > 我认为这是因为我们没有以正确的方式提出问题，因为模型处于端端和离线状态。
> > > > > > > 
> > > > > > > 
> > > > > > > 不，我还问了一些其他问题，例如世界上最长的河流是什么？那么这是什么原因呢？![图像](https://private-user-images.githubusercontent.com/46549527/334070975-62386f20-bdcd-4f37-987d-b593665c7a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAzNzUsIm5iZiI6MTcxNjgxMDA3NSwicGF0aCI6Ii80NjU0OTUyNy8zMzQwNzA5NzUtNjIzODZmMjAtYmRjZC00ZjM3LTk4N2QtYjU5MzY2NWM3YTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGQxODQ5NTA5NGMxYjRiNmRkNTBmNmVkYjQxOWVmNDQzYWM5MWU0NDA0OTliYTBjMThmYTVkYWIyY2QzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0Uj4XVxJRqyvPazAh4XknjHtvNcIciZnQO38rYJTS4)
> > > > > 
> > > > > 
> > > > > 事实上，我正在经历同样的情况。出于这个原因，我在 PC 上部署了 llama3 进行比较。在 PC 上，llama3 的效果要好得多，所以我想知道 mnn 格式的模型是否存在问题？
> > > > 
> > > > 
> > > > 我从作者提供的链接下载了模型，模型下载路径： https://github.com/wangzhaode/mnn-llm/releases 我不太确定这是否是模型格式问题，我准备尝试按照步骤将 onnx 转换为 mnn
> > > 
> > > 
> > > 这就是我目前正在做的事情，只能通过消除来找到问题。
> > 
> > 
> > Can you let me know if you have any new progress or solve the problem？thanks
> 
> Sorry, I don't have a solution for this at the moment......


I also don't have a solution either，This is really a headache inducing mistake
