### ISSUE TITLE
2024.6.12 master分支Android构建报错

### ISSUE THREAD

**Issue by bulletProofCat** [wangzhaode/mnn-llm#199]
看起来错误原因是这个commit修改了llm.hpp，但是Android的jni代码并没有做同步的修改导致：

https://github.com/wangzhaode/mnn-llm/commit/23b924957cd48e832726932abb04e57b780e520e

Android出问题的代码：

https://github.com/wangzhaode/mnn-llm/blob/84a52f401fde86db477c55e839f167bb8f464fb2/android/app/src/main/jni/llm_mnn_jni.cpp

上面这个JNI代码中：
llm->load(model_dir)
llm->load_progress()
都因为hpp声明变了，但是JNI代码没有同步修改而有报错

**Comment by wangzhaode** [comment]
是的，最新的代码已经修改，多谢反馈
