### ISSUE TITLE
qwen2-1.5B get wront results on x86 and macos

### ISSUE THREAD

**Issue by xingjinglu** [wangzhaode/mnn-llm#200]
./cli_demo ../ios/mnn-llm/Qwen2-1.5B-Instruct-MNN
model path is ../ios/mnn-llm/Qwen2-1.5B-Instruct-MNN
libc++abi: terminating due to uncaught exception of type nlohmann::json_abi_v3_11_3::detail::type_error: [json.exception.type_error.306] cannot use value() with null
zsh: abort      ./cli_demo ../ios/mnn-llm/Qwen2-1.5B-Instruct-MNN

**Comment by xingjinglu** [comment]
It is cuased with wrong used.
`./cli_demo Qwen2-1.5B-Instruct-MNN/config.json`

but with the above command, I encounter some others errors:

model path is Qwen2-1.5B-Instruct-MNN/config.json
The device support i8sdot:0, support fp16:0, support i8mm: 0
### is_single_ = 1, is_disk_embedding_ = 1
load tokenizer
tokenizer_type = 3
load tokenizer Done
load Qwen2-1.5B-Instruct-MNN/qwen2-1.5b-int4.mnn ... Invalidate buffer to create MNN Module
Done!

Q: 您好

A: Segmentation fault

**Comment by kunlun-yangjianli** [comment]
我在android的版本上也发现了这个问题，请问你这边找到原因了么

**Comment by wangzhaode** [comment]
> load Qwen2-1.5B-Instruct-MNN/qwen2-1.5b-int4.mnn ... Invalidate buffer to create MNN Module

这个问题应该是模型文件没有正确下载，可以核对一下模型文件的SHA256值对不对

**Comment by wangzhaode** [comment]
代码更新一下试试MacOS是否正常

**Comment by kunlun-yangjianli** [comment]
> 代码更新一下试试MacOS是否正常

抱歉，当前解决了，但是忘记关闭了。 原因是android编译的时候，默认选择armv82的版本，但是手机只支持armv8a，导致异常，改为armv8a就好了

**Comment by xingjinglu** [comment]
> 代码更新一下试试MacOS是否正常

试过最新的代码，仍然有错

**Comment by xingjinglu** [comment]
> SHA256值

正确值是多少？

**Comment by xingjinglu** [comment]
qwen2-1.5B是有GQA的，mnn-llm支持GQA么

**Comment by xingjinglu** [comment]
> > 代码更新一下试试MacOS是否正常
> 
> 试过最新的代码，仍然有错

MNN的llm_demo可以正常跑了
