### ISSUE TITLE
请问whisper、paraformer等语音识别模型能用mnn-llm跑吗？

### ISSUE THREAD

**Issue by niusmall** [wangzhaode/mnn-llm#205]
如题，llm-export似乎只能转换已支持的qwen等模型，对于语音识别大模型，例如whisper、paraformer等模型，可以用mnn-llm部署吗？

**Comment by wangzhaode** [comment]
可以部署，但是现在还没有例子；如果您感兴趣可以将whisper先转换成onnx 然后转换为mnn
