### ISSUE TITLE
android端推理crash

### ISSUE THREAD

**Issue by robben225** [wangzhaode/mnn-llm#207]
我按照readme里步骤，将编译出的so和模型推到android设备的/data/local/tmp目录下，在执行./cli_demo ./Qwen2-1.5B-Instruct-MNN/config.json时，模型可以加载成功，但是在对话时，就会crash。

/data/local/tmp # ./cli_demo ./mnn-llm/Qwen2-1.5B-Instruct-MNN/config.json                                                                                                 
model path is ./mnn-llm/Qwen2-1.5B-Instruct-MNN/config.json
single_ = 1, is_disk_embedding_ = 1
load tokenizer
tokenizer_type = 3
load tokenizer Done
load ./mnn-llm/Qwen2-1.5B-Instruct-MNN/qwen2-1.5b-int4.mnn ... Done!

Q: hello

A: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
Aborted

**Comment by robben225** [comment]
代码和模型版本不一致导致的

**Comment by dengwhao** [comment]
@robben225  具体是哪里不一致，我用魔塔和huggingface上下载的模型都试过，和你报同样的错误，但是Qwen1.5-0.5B就没有报错
