### ISSUE TITLE
clone 了最新的代码， 然后安装了apk，下载了模型，然后push进去了，app闪退了

### ISSUE THREAD

**Issue by 1eas7** [wangzhaode/mnn-llm#214]
做了以下步骤：
1、克隆了最新代码
2、apk编译成功
3、git clone https://www.modelscope.cn/zhaode/Qwen-1_8B-Chat-MNN.git  把模型复制下来了
4、adb push ./Qwen-1_8B-Chat-MNN /data/local/tmp/mnn-llm/
5、然后运行选择这个文件夹闪退了，点加载以后闪退了
![image](https://github.com/user-attachments/assets/e3d0b0a4-9ddb-4960-91d7-602b371a5abf)

是忘记哪个步骤了吗？ 模型要在转换一次吗？

**Comment by 1eas7** [comment]
报错信息
![image](https://github.com/user-attachments/assets/30f07af4-22a8-4ed8-a3d9-46c37eac281b)

**Comment by poached-egg** [comment]
> 仓库里的Android App打包存在问题，会导致mnn相关依赖库未打包至apk，个人建议是将JNI与mnn依赖库分开编译进行打包。

你好，请问怎么分开编译打包

**Comment by FranzKafkaYu** [comment]
> > 仓库里的Android App打包存在问题，会导致mnn相关依赖库未打包至apk，个人建议是将JNI与mnn依赖库分开编译进行打包。
> 
> 你好，请问怎么分开编译打包

在JNI层添加新的CMake配置，将MNN依赖库进行导入。

**Comment by 1eas7** [comment]
> > > 仓库里的Android App打包存在问题，会导致mnn相关依赖库未打包至apk，个人建议是将JNI与mnn依赖库分开编译进行打包。
> > 
> > 
> > 你好，请问怎么分开编译打包
> 
> 在JNI层添加新的CMake配置，将MNN依赖库进行导入。

CMake配置要怎么写呢？ 可以参考git的历史记录吗？

**Comment by wangzhaode** [comment]
之前需要手动拷贝so，最新代码在cmake里做了so的拷贝可以了

**Comment by dengwhao** [comment]
@1eas7 你是全部模型导入的时候都会导致app闪退吗？还是只有特定的模型会出现这个情况？
