### ISSUE TITLE
在Android 上加载Gamma2 2B的时候Demo App 闪退

### ISSUE THREAD

**Issue by chenminjun-web** [wangzhaode/mnn-llm#219]
在Android 上加载Gamma2 2B模型的时候出现闪退， log 可以看到错误信息：

~~yq1Y_vTI5KYKtFU95mhztQ==/com.mnn.llm-uMt5RTqHtKADdXgi7jGKAA==/lib/arm64/libMNN.so (MNN::MemoryLoader::read(char*, long)+80) (BuildId: f8c768fdc107c9e3dd3d4e5907ceeee4d9c58ec5)

奇怪的是， 如果先选择QWen2 1.5B模型运行， 然后退出Demo App， 再次打开APP选择Gamma2 2B模型， 这时却能正常加载运行。

**Comment by dengwhao** [comment]
@chenminjun-web 可以确信，你并没有跑在Gamma2 2B模型上。我也遇到了这个情况，你把app clear data一下，他还是会闪退
