### ISSUE TITLE
mnn-llm 使用cuda 后端执行时，每次结果都是不一样的。

### ISSUE THREAD

**Issue by BaofengZan** [wangzhaode/mnn-llm#222]
<img width="628" alt="image" src="https://github.com/user-attachments/assets/51e52d3f-8aed-4795-9356-f9dfcd658234">

模型使用了fuse attention ， cpu端结果正常，切换成cuda后，提示上面的问题，并且每次结果都是不同的。是因为是不支持的问题吗？

**Comment by wangzhaode** [comment]
CUDA后端还不支持fuse attention的算子

**Comment by BaofengZan** [comment]
好的。 感谢

**Comment by BaofengZan** [comment]
另外，我导出mnn模型时，不选用fuseAttention，但是使用cuda后端时，运行多次，结果有时候对，有时候不对？这种可能是什么原因呢？
