### ISSUE TITLE
请教大佬，/cli_demo  Load Cache file error.如何解决

### ISSUE THREAD

**Issue by longyangzhang** [wangzhaode/mnn-llm#228]
$ ./cli_demo ../Qwen2.5-0.5B-Instruct-MNN/config.json
model path is ../Qwen2.5-0.5B-Instruct-MNN/config.json
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
Can't open file:.tempcache
Load Cache file error.
### is_single_ = 1
load tokenizer
tokenizer_type = 3
load tokenizer Done
load ../Qwen2.5-0.5B-Instruct-MNN/llm.mnn ... Invalidate buffer to create MNN Module
Load Module Done!
[1]    98477 segmentation fault  ./cli_demo ../Qwen2.5-0.5B-Instruct-MNN/config.json

**Comment by wangzhaode** [comment]
错误信息是：Invalidate buffer to create MNN Module

看起来模型文件不对，你核对一下是否正确下载或者导出

**Comment by longyangzhang** [comment]
我有再重新多下载几个模式试了一下还是报同样的错误。模型下载地址git clone https://www.modelscope.cn/zhaode/Qwen2.5-0.5B-Instruct-MNN.git

**Comment by wangzhaode** [comment]
load ../Qwen2.5-0.5B-Instruct-MNN/llm.mnn ... Invalidate buffer to create MNN Module
Load Module Done!

看起来就是模型文件不对，你看一下自己手机上的文件大小是否与仓库里的模型文件大小一致

**Comment by longyangzhang** [comment]
已解决，从huggingface下载模型是可以的。感谢佬的回复!

**Comment by longyangzhang** [comment]
再请教以下佬，llm-export支持t5的转换吗？mnn-llm支持t5吗

**Comment by longyangzhang** [comment]
佬，有wx群吗？想加入
