### ISSUE TITLE
大佬好，请问如何统计每秒 token 数，例如：MLCChat 上输出的 prefill:xx tok/s decode:xx tok/s

### ISSUE THREAD

**Issue by XTaoWang** [wangzhaode/mnn-llm#231]

**Comment by wangzhaode** [comment]
在命令行中测试会直接打印速度的

**Comment by XTaoWang** [comment]
怎么测试了？不同的手机配置和参数不同，我理解 prefill:xx tok/s decode:xx tok/s 生成的数值应该都不同？求大佬指教

**Comment by wangzhaode** [comment]
adb shell "cd /data/local/tmp && export LD_LIBRARY_PATH=. && ./cli_demo ./Qwen2-1.5B-Instruct-MNN/config.json"

README里有介绍的，直接使用adb运行demo就可以打印性能

**Comment by XTaoWang** [comment]
> adb shell "cd /data/local/tmp && export LD_LIBRARY_PATH=. && ./cli_demo ./Qwen2-1.5B-Instruct-MNN/config.json"
> 
> README里有介绍的，直接使用adb运行demo就可以打印性能

阅读 c++ 代码发现 
void Llm::print_speed() {
    auto prefill_s = prefill_us_ * 1e-6;
    auto decode_s = decode_us_ * 1e-6;
    auto total_s = prefill_s + decode_s;
    printf("\n#################################\n");
    printf(" total tokens num  = %d\n", prompt_len_ + gen_seq_len_);
    printf("prompt tokens num  = %d\n", prompt_len_);
    printf("output tokens num  = %d\n", gen_seq_len_);
    printf("  total time = %.2f s\n", total_s);
    printf("prefill time = %.2f s\n", prefill_s);
    printf(" decode time = %.2f s\n", decode_s);
    printf("  total speed = %.2f tok/s\n", (prompt_len_ + gen_seq_len_) / total_s);
    printf("prefill speed = %.2f tok/s\n", prompt_len_ / prefill_s);
    printf(" decode speed = %.2f tok/s\n", gen_seq_len_ / decode_s);
    printf("   chat speed = %.2f tok/s\n", gen_seq_len_ / total_s);
    printf("##################################\n");
}
发现这块可以获取到。
