### ISSUE TITLE
libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found

### ISSUE THREAD

**Issue by Qrrrr** [wangzhaode/mnn-llm#239]
想问一下这个是什么问题
![111](https://github.com/user-attachments/assets/bfe71357-0870-49cf-9984-2ce422e5c356)

**Comment by Qrrrr** [comment]
@wangzhaode 大佬可以帮忙看看吗

**Comment by wangzhaode** [comment]
prompt的内容是什么？或者是否能给一下crash的堆栈信息

**Comment by Qrrrr** [comment]
prompt的内容是：<img>/data/local/tmp/2.png</img>Can you describe the image? 不过应该和prompt无关，我刚刚试了以下不加prompt他也会报这个错。想问一下如何打印crash堆栈信息...

**Comment by Qrrrr** [comment]
> prompt的内容是什么？或者是否能给一下crash的堆栈信息

prompt的内容是<img>/data/local/tmp/2.png</img>Can you describe the image?，应该和prompt无关，我刚刚试了把prompt删了好像也会报这个错在和他对话的时候。想问一下crash堆栈信息如何打印...

**Comment by Qrrrr** [comment]
> prompt的内容是什么？或者是否能给一下crash的堆栈信息
我用adb logcat *:S AndroidRuntime:E libc:* Crash:* *:F查到的报错信息是这样的：
12-30 11:51:33.974 14202 14202 I libc    : cli_demo: received profiling signal with si_value: 1
12-30 11:51:33.975 14200 14200 I libc    : sh: received profiling signal with si_value: 1
12-30 11:51:46.117 14202 14202 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14202 (cli_demo), pid 14202 (cli_demo)
12-30 11:51:46.346 14214 14214 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-30 11:51:46.346 14214 14214 F DEBUG   : Build fingerprint: 'Redmi/gold/gold:14/UP1A.231005.007/V816.0.3.0.UNQMIXM:user/release-keys'
12-30 11:51:46.346 14214 14214 F DEBUG   : Revision: '0'
12-30 11:51:46.346 14214 14214 F DEBUG   : ABI: 'arm64'
12-30 11:51:46.346 14214 14214 F DEBUG   : Timestamp: 2024-12-30 11:51:46.331117190+0800
12-30 11:51:46.346 14214 14214 F DEBUG   : Process uptime: 14s
12-30 11:51:46.346 14214 14214 F DEBUG   : Cmdline: ./cli_demo Qwen2-VL-2B-Instruct-MNN/config.json prompt.txt
12-30 11:51:46.346 14214 14214 F DEBUG   : pid: 14202, tid: 14202, name: cli_demo  >>> ./cli_demo <<<
12-30 11:51:46.346 14214 14214 F DEBUG   : uid: 2000
12-30 11:51:46.346 14214 14214 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
12-30 11:51:46.346 14214 14214 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-30 11:51:46.346 14214 14214 F DEBUG   : Abort message: 'terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found'
12-30 11:51:46.346 14214 14214 F DEBUG   :     x0  0000000000000000  x1  000000000000377a  x2  0000000000000006  x3  0000007fc38d1fb0
12-30 11:51:46.346 14214 14214 F DEBUG   :     x4  646277641f736766  x5  646277641f736766  x6  646277641f736766  x7  7f7f7f7f7f7f7f7f
12-30 11:51:46.346 14214 14214 F DEBUG   :     x8  00000000000000f0  x9  000000777c682de8  x10 0000000000000001  x11 000000777c6febf0
12-30 11:51:46.346 14214 14214 F DEBUG   :     x12 0000007781ca6020  x13 000000007fffffff  x14 0000000001bdb610  x15 000006f939b12e57
12-30 11:51:46.346 14214 14214 F DEBUG   :     x16 000000777c76d9f8  x17 000000777c747500  x18 0000007780e80000  x19 000000000000377a
12-30 11:51:46.346 14214 14214 F DEBUG   :     x20 000000000000377a  x21 00000000ffffffff  x22 0000007fc38d20e0  x23 0000007fc38d2120
12-30 11:51:46.346 14214 14214 F DEBUG   :     x24 0000007fc38d21d0  x25 0000007fc38d2370  x26 b4000076f038d998  x27 0000007fc38d2740
12-30 11:51:46.346 14214 14214 F DEBUG   :     x28 b4000076f038d980  x29 0000007fc38d2030
12-30 11:51:46.346 14214 14214 F DEBUG   :     lr  000000777c6ef238  sp  0000007fc38d1f90  pc  000000777c6ef264  pst 0000000000001000
12-30 11:51:46.346 14214 14214 F DEBUG   : 14 total frames
12-30 11:51:46.346 14214 14214 F DEBUG   : backtrace:
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: Function names and BuildId information is missing for some frames due
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: found under the lib/ directory are readable.
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: On this device, run setenforce 0 to make the libraries readable.
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: Unreadable libraries:
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE:   /data/local/tmp/cli_demo
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE:   /data/local/tmp/libMNN.so
12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE:   /data/local/tmp/libllm.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #00 pc 0000000000094264  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 84a42637b3a421b801818f5793418fca)
12-30 11:51:46.346 14214 14214 F DEBUG   :       #01 pc 000000000023e1cc  /data/local/tmp/libMNN.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #02 pc 000000000023dbd8  /data/local/tmp/libMNN.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #03 pc 000000000023da98  /data/local/tmp/libMNN.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #04 pc 00000000002582cc  /data/local/tmp/libMNN.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #05 pc 00000000002582a8  /data/local/tmp/libMNN.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #06 pc 00000000000ac950  /data/local/tmp/libllm.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #07 pc 00000000000e4f00  /data/local/tmp/libllm.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #08 pc 00000000000df468  /data/local/tmp/libllm.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #09 pc 000000000009c0c8  /data/local/tmp/libllm.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #10 pc 000000000009703c  /data/local/tmp/libllm.so
12-30 11:51:46.346 14214 14214 F DEBUG   :       #11 pc 0000000000003f3c  /data/local/tmp/cli_demo
12-30 11:51:46.346 14214 14214 F DEBUG   :       #12 pc 0000000000004628  /data/local/tmp/cli_demo
12-30 11:51:46.346 14214 14214 F DEBUG   :       #13 pc 000000000008c798  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 84a42637b3a421b801818f5793418fca)

**Comment by wangzhaode** [comment]
可以编译成debug版本运行一下 会有符号信息；或者先在电脑上测试一下看看

**Comment by Qrrrr** [comment]
> > prompt的内容是什么？或者是否能给一下crash的堆栈信息
> > 我用adb logcat _:S AndroidRuntime:E libc:_ Crash:* *:F查到的报错信息是这样的：
> > 12-30 11:51:33.974 14202 14202 I libc    : cli_demo: received profiling signal with si_value: 1
> > 12-30 11:51:33.975 14200 14200 I libc    : sh: received profiling signal with si_value: 1
> > 12-30 11:51:46.117 14202 14202 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14202 (cli_demo), pid 14202 (cli_demo)
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : Build fingerprint: 'Redmi/gold/gold:14/UP1A.231005.007/V816.0.3.0.UNQMIXM:user/release-keys'
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : Revision: '0'
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : ABI: 'arm64'
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : Timestamp: 2024-12-30 11:51:46.331117190+0800
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : Process uptime: 14s
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : Cmdline: ./cli_demo Qwen2-VL-2B-Instruct-MNN/config.json prompt.txt
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : pid: 14202, tid: 14202, name: cli_demo  >>> ./cli_demo <<<
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : uid: 2000
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : Abort message: 'terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found'
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x0  0000000000000000  x1  000000000000377a  x2  0000000000000006  x3  0000007fc38d1fb0
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x4  646277641f736766  x5  646277641f736766  x6  646277641f736766  x7  7f7f7f7f7f7f7f7f
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x8  00000000000000f0  x9  000000777c682de8  x10 0000000000000001  x11 000000777c6febf0
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x12 0000007781ca6020  x13 000000007fffffff  x14 0000000001bdb610  x15 000006f939b12e57
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x16 000000777c76d9f8  x17 000000777c747500  x18 0000007780e80000  x19 000000000000377a
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x20 000000000000377a  x21 00000000ffffffff  x22 0000007fc38d20e0  x23 0000007fc38d2120
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x24 0000007fc38d21d0  x25 0000007fc38d2370  x26 b4000076f038d998  x27 0000007fc38d2740
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     x28 b4000076f038d980  x29 0000007fc38d2030
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :     lr  000000777c6ef238  sp  0000007fc38d1f90  pc  000000777c6ef264  pst 0000000000001000
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : 14 total frames
> > 12-30 11:51:46.346 14214 14214 F DEBUG   : backtrace:
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: Function names and BuildId information is missing for some frames due
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: found under the lib/ directory are readable.
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: On this device, run setenforce 0 to make the libraries readable.
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE: Unreadable libraries:
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE:   /data/local/tmp/cli_demo
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE:   /data/local/tmp/libMNN.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :   NOTE:   /data/local/tmp/libllm.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #00 pc 0000000000094264  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 84a42637b3a421b801818f5793418fca)
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #1 pc 000000000023e1cc  /data/local/tmp/libMNN.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #2 pc 000000000023dbd8  /data/local/tmp/libMNN.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #3 pc 000000000023da98  /data/local/tmp/libMNN.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #4 pc 00000000002582cc  /data/local/tmp/libMNN.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #5 pc 00000000002582a8  /data/local/tmp/libMNN.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #6 pc 00000000000ac950  /data/local/tmp/libllm.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #7 pc 00000000000e4f00  /data/local/tmp/libllm.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #8 pc 00000000000df468  /data/local/tmp/libllm.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #9 pc 000000000009c0c8  /data/local/tmp/libllm.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #10 pc 000000000009703c  /data/local/tmp/libllm.so
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #11 pc 0000000000003f3c  /data/local/tmp/cli_demo
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #12 pc 0000000000004628  /data/local/tmp/cli_demo
> > 12-30 11:51:46.346 14214 14214 F DEBUG   :       #13 pc 000000000008c798  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 84a42637b3a421b801818f5793418fca)

我改用MNN了，用llmexport转后的VL模型已经跑通了，不过我用modelscope上下载的模型还是会报错..

**Comment by wangzhaode** [comment]
> ，用llmexport转后的VL模型已经跑通了，不过我用modelscope上下载的模型还是会报错..

ok 最近多模态的模型有些更新 代码版本上可能有些没对齐 后续会对齐一下
