### ISSUE TITLE
问到第三个问题的时候直接崩溃

### ISSUE THREAD

**Issue by starfire-lzd** [wangzhaode/mnn-llm#27]
![image](https://user-images.githubusercontent.com/12759942/229276619-dda83a3c-bc92-408d-a642-026a3bfb047a.png)

**Comment by iamblue** [comment]
+1 Can't run session because not resized

**Comment by wangzhaode** [comment]
更新一下代码试试看

**Comment by wangzhaode** [comment]
> +1 Can't run session because not resized
> 
> 

更新一下试试

**Comment by iamblue** [comment]
@wangzhaode 我發現似乎好像是 
```
./cli_demo -g 11
```
有填寫 -g 的話就會有，如果純 ./cli_demo 就沒有

**Comment by wangzhaode** [comment]
> @wangzhaode 我發現似乎好像是
> 
> ```
> ./cli_demo -g 11
> ```
> 
> 有填寫 -g 的話就會有，如果純 ./cli_demo 就沒有

哦， 那就是因为随着会话轮数增多，输入的数据量变大，导致显存不足resize失败
