### ISSUE TITLE
从源码编译MNN时出现错误

### ISSUE THREAD

**Issue by okatu-loli** [wangzhaode/mnn-llm#34]
环境：Windows Server 2022

按步骤运行命令报错：
```
PS C:\Users\Administrator\Desktop\ai\chatglmcplus\MNN\build> make -j8
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by wangzhaode** [comment]
```
# Visual Studio xxxx Developer Command Prompt
powershell
git clone https://github.com/alibaba/MNN.git
cd MNN
mkdir build
cmake -G "Ninja" ..
ninja
```

**Comment by wangzhaode** [comment]
看起来你没有执行`cmake`

Windows推荐使用
ninja来编译，具体编译方法如上

**Comment by ystyle** [comment]
build\express 下没有libMNN_Express.so 

> ```
> # Visual Studio xxxx Developer Command Prompt
> powershell
> git clone https://github.com/alibaba/MNN.git
> cd MNN
> mkdir build
> cmake -G "Ninja" ..
> ninja
> ```

**Comment by wangzhaode** [comment]
Windows下的话只要连接MNN就行了 可以改一下CMakeLists.txt 移除Express的依赖

**Comment by xzh12890** [comment]
不要j8
