### ISSUE TITLE
如何调节多核优化？

### ISSUE THREAD

**Issue by IlysvlVEizbr** [wangzhaode/mnn-llm#37]
纯CPU方案
配置为双路24核E5，64G内存
系统Ubuntu
按Readme流程一路默认make的
实测运行cli_demo时只有3s/word左右的速度，内存占用不到30G，CPU长期占用<10%，top中查看只有单核跑满，其它大部分在空闲
有何建议的解决方案？

可能的诊断信息：
运行cli_demo显示
The device support dot:0, support fp16:0, support i8mm: 0
Can't Find type=2 backend, use 3 instead

**Comment by wildkid1024** [comment]
作者没写多进程，所以实际上只有一个core在跑，cuda优化好像也有一堆问题。

**Comment by wangzhaode** [comment]
```
BackendConfig cpuBackendConfig;
config.type          = MNN_FORWARD_CPU;
config.numThread     = 4; // 修改一下这里的线程数
```

**Comment by IlysvlVEizbr** [comment]
> ```
> BackendConfig cpuBackendConfig;
> config.type          = MNN_FORWARD_CPU;
> config.numThread     = 4; // 修改一下这里的线程数
> ```

之前就找到过这个位置，尝试过修改，numThread直接改成了32，但效果不佳，大部分时间还是只有单核运行，少部分时间多核调用起来了，但是这些CPU核的占用还是吃不满

**Comment by wildkid1024** [comment]
实际上上述配置只修改了线程，但多核是多进程。所以改配置IO会快一些，但算力并没有提高。
实现cpu多进程管理并不简单，相比之下cuda多卡支持可能更好实现一些？

**Comment by wildkid1024** [comment]
单机多卡是个困难的问题，会涉及到多卡之间的通信，目前还没看到mnn有接口能够支持。
