### ISSUE TITLE
运行 crash

### ISSUE THREAD

**Issue by sgxu** [wangzhaode/mnn-llm#39]
你好， 按照提示， 自己转了一遍模型放到demo中运行出现了 crash：

Q: 用Python帮我写一段快速排序代码

A: Broad cast error, dim1 = 4, dim2 = 11
Compute Shape Error for /transformer/layers.0/attention/Add_3_output_0
Can't run session because not resized
[1]    33204 segmentation fault  ./cli_demo

请问是转模型过程中哪个环节出了问题吗 ？

**Comment by wangzhaode** [comment]
是不是显存设置不正确呢

**Comment by sgxu** [comment]
我是在 imac（32GB） 上 CPU 运行的， 直接下载 int8 模型是可以运行出正确结果的， 但是自己重新走了一遍 pytorch->onnx->mnn 这个流程， 自己转的模型会出现上面的问题

**Comment by sgxu** [comment]
而且我用 BeyondCompare对比了 下载的 onnx 以及自己转的 onnx， 并不是 bitwsie 一致， 
onnx模型文件的前面少部分是不一致的， 后面绝大部分是一致的，难道onnx前面的不一致的部分是模型结构，后面相同的部分是权重 ？
请问和 onnx 版本有关吗 ？

**Comment by wangzhaode** [comment]
1. 看起来是你在重新转换时有些shape固定了 不支持动态形状导致的；
2. 你自己转换出来的模型应该是计算图部分有区别；权重部分相同；

**Comment by sgxu** [comment]
但是我是严格按照你给的脚本进行的呢 ：
```
def glm_to_onnx():
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True, resume_download=True).float().cpu()
    model_export(model,
                model_args=(
                    torch.randn(4, 1, 4096),
                    torch.tensor([[[[False, False, False,  True],
                                    [False, False, False,  True],
                                    [False, False, False,  True],
                                    [False, False, False, False]]]]),
                    torch.tensor([[[0, 1, 2, 3], [0, 0, 0, 1]]]),
                    torch.zeros(2, 0, 1, 32, 128)
                ),
                output_path= "dyn_model/glm_block_{}.onnx".format(sys.argv[1]),
                ordered_input_names=["inputs_embeds", "attention_mask", "position_ids", "past_key_values"],
                output_names=["hidden_states", "presents"],
                dynamic_axes={
                    "inputs_embeds" : { 0: "seq_len" },
                    "attention_mask" : { 2: "seq_len", 3: "seq_len" },
                    "position_ids" : { 2: "seq_len" },
                    "past_key_values" : { 1: "history_len" }
                },
                opset= 14)
```
请问这边哪里需要修改吗 ？
咱们的 pytorch 版本， protobuf 版本， onnx 版本有没有可能造成影响吗 ？

**Comment by sgxu** [comment]
我发现下载的 onnx 模型使用的是 pytorch 1.12.1, 
而我使用的是 pytorch 1.13.1， 然后我怀疑是 版本的问题，我也换成了 pytorch 1.12.1， 然后再 onnx -> mnn， 然后又出现了不一样的运行期错误：
```
Q:
A: Broad cast error, dim1 = 4, dim2 = 11
Compute Shape Error for onnx::Unsqueeze_718
Can't run session because not resized
[1]    24656 segmentation fault  ./cli_demo
```
其实我把 pytorch 版本从 1.13.1 换成了 pytorch 1.12.1 后， 在 onnx->mnn 的转模型阶段也会提示错误：
Broad cast error, dim1 = 1, dim2 = 1
但是依然可以生成 mnn 模型（该模型运行会出错 Compute Shape Error for onnx::Unsqueeze_718）
但是 pytorch 1.13.1 转成的 onnx, 然后再转 mnn 的过程中不会提示错误， 仅仅是推理报错（Compute Shape Error for /transformer/layers.0/attention/Add_3_output_0）

**Comment by sgxu** [comment]
我发现下载的 onnx 模型使用的是 pytorch 1.12.1, 
而我使用的是 pytorch 1.13.1， 然后我怀疑是 版本的问题，我也换成了 pytorch 1.12.1， 然后再 onnx -> mnn， 然后又出现了不一样的运行期错误：
```
Q:
A: Broad cast error, dim1 = 4, dim2 = 11
Compute Shape Error for onnx::Unsqueeze_718
Can't run session because not resized
[1]    24656 segmentation fault  ./cli_demo
```

**Comment by sgxu** [comment]
有的， 替换了， 应该是严格按照工程中的说明操作的，

**Comment by Truoji** [comment]
请问一下，我也遇到相同的问题，请问您解决了吗？
