### ISSUE TITLE
和LLMA.cpp相比，为什么性能会差这么多？

### ISSUE THREAD

**Issue by yhyu13** [wangzhaode/mnn-llm#42]
是指令集的区别？LLMA.cpp用的是AVX x86和NEO arm。chatgtp4all-j 在m1上4核心可以跑到3 token /s
还是模型架构优化上的差异？

**Comment by mytbk** [comment]
看了下源码 https://github.com/wangzhaode/ChatGLM-MNN/blob/master/src/chat.cpp#L111 默认只用4个CPU线程。
奇怪的是，我把这个值调大了之后，cli_demo 的 CPU 占用的确变大了，但也没有到我设的那个值。

**Comment by wildkid1024** [comment]
详细阅读了本项目的的源码，发现有几项可能会影响性能问题，虽然有些问题我们已经实现了一些简单的解决方案：
1. 多线程数没有根据cpu核数自动判别，也没加入到模型运行的参数设置中
2.  有很大几率会出现segment error，建议添加history关闭选项，并使用纯CPU的方式运行，有些低性能机器并不能处理多轮对话
3.  第2个问题另外一个原因在https://github.com/wangzhaode/ChatGLM-MNN/blob/master/src/chat.cpp#L135，模型占用的大小和实际占用的显存大小并不一致，某些低配置GPU上会导致地址越界，在int4等量化模型下也没降低显存，怀疑onnx或MNN仍旧使用fp32加载的模型，使用MNN的量化工具重新量化可能有效
4. onnx模型拆了某些算子，原本cuda friendly的计算图被打乱，目前还不清楚有没有torch直接到MNN的方案
5. 并发困难，因为接收的是静态输入，并发输入会导致同名变量的shape不一致，程序会直接core掉
6. 不知道MNN有没有模型并行的多卡运行的API(理论上讲训练时也应该数据并行)，翻了半天没找到，期待后续有关注

以上问题是在实际运行中碰到的，也希望能够给正准备优化该项目的同学一些启发。
