### ISSUE TITLE
make -j8的时候报错

### ISSUE THREAD

**Issue by reddhu** [wangzhaode/mnn-llm#47]
ChatGLM-MNN-master/include/httplib.h:3010:14: error: missing space between ‘""’ and suffix identifier
using udl::operator""_t;
ChatGLM-MNN-master/include/httplib.h:3010:22: error: expected ‘;’ before ‘STRING_USERDEF’ token
using udl::operator""_t;

**Comment by wildkid1024** [comment]
确定代码没有改动？

**Comment by reddhu** [comment]
没有任何改动，按照步骤来的


3. Build and Run
Mac/Linux/Windows:

mkdir build
cd build
cmake ..
make -j8
./cli_demo # cli demo
./web_demo # web ui demo

到这一步的make -j8的时候就报错了，cli_demo是正常的，可以运行，web_demo就没有生成

**Comment by wangzhaode** [comment]
是什么操作系统 编译器

**Comment by reddhu** [comment]
centos 
cmake-3.26.3
