### ISSUE TITLE
How to enable fp16？

### ISSUE THREAD

**Issue by duzx16** [wangzhaode/mnn-llm#5]
运行的时候第一行输出
```
The device support dot:0, support fp16:0, support i8mm: 0
```
应该是没有使用fp16？导致推理的速度比PyTorch慢很多
环境是NVIDIA A100 + CUDA 11.4

**Comment by wangzhaode** [comment]
这个log是CPU的info； CUDA是支持fp16的 precision设置为low就是fp16; 
现在的代码CUDA默认是使用的fp16；您把显存设置大一些试试看

**Comment by wangzhaode** [comment]
我目前还没有显存>=13G的显卡可用，所以还没有测试对比过CUDA fp16得性能对比

**Comment by duzx16** [comment]
> 这个log是CPU的info； CUDA是支持fp16的 precision设置为low就是fp16; 现在的代码CUDA默认是使用的fp16；您把显存设置大一些试试看； 或者把这行代码的`cuda`直接改为true：
> 
> https://github.com/wangzhaode/ChatGLM-MNN/blob/2997835fadab81f57dba9f1d37d33b40b880471d/src/chat.cpp#L143

已经把显存改到足以放下整个模型了。那速度差得有点多，生成大概200个token的内容，PyTorch是11秒，MNN是80秒

**Comment by duzx16** [comment]
> > 这个log是CPU的info； CUDA是支持fp16的 precision设置为low就是fp16; 现在的代码CUDA默认是使用的fp16；您把显存设置大一些试试看； 或者把这行代码的`cuda`直接改为true：
> > https://github.com/wangzhaode/ChatGLM-MNN/blob/2997835fadab81f57dba9f1d37d33b40b880471d/src/chat.cpp#L143
> 
> 已经把显存改到足以放下整个模型了。那速度差得有点多，生成大概200个token的内容，PyTorch是11秒，MNN是80秒

重新测试了一下，MNN是32秒，但是还是跟PyTorch差很多

**Comment by wangzhaode** [comment]
> 

MNN CUDA性能一般是比Pytorch好的；这个模型我找设备测试一下

**Comment by wangzhaode** [comment]
- 这里的第二个参数也要改成`true`； 因为我是针对小显存实现的，直接把最后的`lm_head`固定到CPU了；
https://github.com/wangzhaode/ChatGLM-MNN/blob/6229dc31bb70baf42d67a311694e044bc34dd5f5/src/chat.cpp#L131

- 目前的写法回存在CUDA->CPU的memcpy开销；对于大显存的情况还可以优化；

**Comment by duzx16** [comment]
> * 这里的第二个参数也要改成`true`； 因为我是针对小显存实现的，直接把最后的`lm_head`固定到CPU了；
>   https://github.com/wangzhaode/ChatGLM-MNN/blob/6229dc31bb70baf42d67a311694e044bc34dd5f5/src/chat.cpp#L131
> * 目前的写法存在CUDA->CPU的memcpy开销；对于大显存的情况还可以优化；

改了之后模型的生成结果直接崩了
![image](https://user-images.githubusercontent.com/28836239/228418863-70e5d7e1-67dc-439a-bc03-78c9ccec9026.png)

**Comment by qijiaxing** [comment]
我用的A100，也发现推理速度比较慢。而且是随着生成越来越慢。关注一下这个问题。

**Comment by wangzhaode** [comment]
> 我用的A100，也发现推理速度比较慢。而且是随着生成越来越慢。关注一下这个问题。

- CUDA性能正在优化
- 对话轮数多了之后会把历史的内容都作为下一次的prompt输入，所以越跑越慢；如果不需要上下文可以reset一下清空历史；

**Comment by qijiaxing** [comment]
有可能支持batch么？ 如果能支持batch的话，那gpu的利用率就比较高了。

**Comment by wangzhaode** [comment]
> 有可能支持batch么？ 如果能支持batch的话，那gpu的利用率就比较高了。

现在主要是在解决device端显存不足的问题；大显存优化做的还不好哈
