### ISSUE TITLE
微信群，最新信息更新

### ISSUE THREAD

**Issue by wangzhaode** [wangzhaode/mnn-llm#54]
![1](https://github.com/user-attachments/assets/02654c54-2414-4757-a7bd-b4a043bf4fe2)

**Comment by wangzhaode** [comment]
知乎文章：https://zhuanlan.zhihu.com/p/626428648

**Comment by ganxiaolu** [comment]
码过期了诶

**Comment by wangzhaode** [comment]
> 码过期了诶

已更新

**Comment by WalkeR-ZG** [comment]
码过期了大佬~~

**Comment by ChenJiaJian96** [comment]
码过期了大佬~~

**Comment by glide-the** [comment]
码过期了大佬~~

**Comment by wangzhaode** [comment]
> 码过期了大佬~~

已更新

**Comment by ysyisyourbrother** [comment]
大佬，码过期了~

**Comment by gaolongxi** [comment]
码过期了大佬，求更新

**Comment by linzaixing** [comment]
大佬再发个微信码吧

**Comment by wangzhaode** [comment]
> 大佬再发个微信码吧

已更新

**Comment by linzaixing** [comment]
邮件已经收到，谢谢！

**Comment by linzaixing** [comment]
邮件已经收到，谢谢！

**Comment by ewwerpm** [comment]
大佬，二维码已经过期了。能更新一下吗？

**Comment by linzaixing** [comment]
邮件已经收到，谢谢！

**Comment by wanshichenguang** [comment]
码过期了

**Comment by linzaixing** [comment]
邮件已经收到，谢谢！

**Comment by butterluo** [comment]
码过期了...

**Comment by wangzhaode** [comment]
> 码过期了...

群聊超过200人了 不能用二维码进群了orz__

**Comment by wxz1996** [comment]
再来个群？

**Comment by forhonourlx** [comment]
过期啦~大佬再来个群？

**Comment by ggiidd** [comment]
大佬，微信群过期了。

**Comment by LionWY** [comment]
+1

**Comment by XiaotaoChen** [comment]
求加群

**Comment by Icedcocon** [comment]
大佬，带带弟弟！

**Comment by Misby** [comment]
大佬，二维码已经过期了。能更新一下吗？

**Comment by yangyangsu29** [comment]
大佬，二维码已经过期了。能更新一下吗

**Comment by smile2game** [comment]
大佬，二维码已经过期了。能拉我一下吗？
我的邮箱是:2426827419@qq.com

**Comment by JeremyGe07** [comment]
再发我一下吧大佬，谢谢
我的邮箱是 759347921@qq.com

**Comment by linzaixing** [comment]
邮件已经收到，谢谢！

**Comment by hyperbolic-c** [comment]
大佬，群聊求拉！我的邮箱2671440900@qq.com

**Comment by calvin3399** [comment]
大佬，群聊求拉！我的邮箱 20537709@qq.com

**Comment by cdliang11** [comment]
大佬，群聊求拉！我的邮箱 1404056823@qq.com

**Comment by yangyangsu29** [comment]
大佬，群聊求拉！我的邮箱 1175817484@qq.com

**Comment by linzaixing** [comment]
邮件已经收到，谢谢！

**Comment by dignfei** [comment]
过期了，麻烦发一下二维码  850360690@qq.com

**Comment by zhanghao19920218** [comment]
大佬。麻烦发一下二维码2420615378@qq.com

**Comment by paomiannanjue** [comment]
大佬。麻烦发一下二维码850839824@qq.com

**Comment by simple0918** [comment]
大佬。麻烦发一下二维码805474954@qq.com

**Comment by pxEkin** [comment]
大佬。麻烦发一下二维码[707654930@qq.com]

**Comment by ElaineWu66** [comment]
求二维码！感激～elaine.jingyu@gmail.com

**Comment by foukation** [comment]
麻烦发一下二维码，感谢。
邮箱：foukation@gmail.com

**Comment by niusmall** [comment]
大佬求带，4935681@qq.com

**Comment by 946166920** [comment]
求二维码，感谢。
大佬求带，412384199@qq.com

**Comment by LHB116** [comment]
大佬，群聊求拉！我的邮箱 [2570624228@qq.com](mailto:2570624228@qq.com)

**Comment by robben225** [comment]
求二维码，感谢。robben225@126.com

**Comment by GJYWorld** [comment]
求二维码，感谢。crazyorange123@163.com

**Comment by WangHao311** [comment]
求二维码，感谢。[504111878@qq.com](504111878@qq.com)

**Comment by qiankl** [comment]
求二维码，感谢。924237752@qq.com

**Comment by changye-chen** [comment]
求群二维码, 感谢
18782812147@163.com

**Comment by flytair** [comment]
求二维码, 感谢
flytair@outlook.com

**Comment by poached-egg** [comment]
大佬，群聊求拉！我的邮箱 [1464929641@qq.com]

**Comment by Jimskns** [comment]
求拉 1328216681@qq.com

**Comment by Nianqitongs** [comment]
求拉zzd18362885302@163.com

**Comment by liuchenguangqnm** [comment]
安卓集成遇到so内部错误，求拉 1509702763@qq.com

**Comment by FranzKafkaYu** [comment]
请问开发者如何入群呢，想跟大家一起交流

**Comment by FranzKafkaYu** [comment]
> 安卓集成遇到so内部错误，求拉 [1509702763@qq.com](mailto:1509702763@qq.com)

可以共同交流，我集成没问题，现在问题在模型本身

**Comment by mynameisbill2** [comment]
求拉，794408025@qq.com

**Comment by Starrylun** [comment]
求拉， 1755130857@qq.com

**Comment by liuchenguangqnm** [comment]
Hello，感谢回复。我也一度怀疑是模型的问题。


目前我在安卓端用的master分支代码，模型是魔搭的qwen-1.8b-chat，在执行llm::forward函数时崩掉了，请问您有可以正常运行的model吗？


我也尝试用llm-export导出模型，但是遇到了py错误，怀疑是他内部代码有问题。


方便的话咱可以加QQ聊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月2日(周一) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangzhaode/mnn-llm] 微信群，最新信息更新 (Issue #54)




 
求拉， ***@***.***

**Comment by liuchenguangqnm** [comment]
> > Android集成遇到如此内部错误，求拉[1509702763@qq.com](mailto:1509702763@qq.com)
> 
> 可以共同交流，我集成没问题，现在问题在模型本身

感谢回复。我也一度怀疑是模型的问题。目前我在安卓端用的master分支代码，模型是魔搭的qwen-1.8b-chat，在执行llm::forward函数时崩掉了，请问你有可以正常运行的模型吗？
我使用llm-export导出模型也没能成功。

**Comment by Zhang-Shubo** [comment]
求加微信交流，591583861@qq.com

**Comment by wangzhaode** [comment]
更新了一下群二维码，有需要可以进群

**Comment by Maybe1297** [comment]
二维码过期了 佬

**Comment by Maybe1297** [comment]
求加微信交流，1057691406@qq.com

**Comment by longyangzhang** [comment]
求微信二维码,2435518172@qq.com

**Comment by XTaoWang** [comment]
有微信群吗

**Comment by kavie-c** [comment]
求微信二维码：1351420688@qq.com

**Comment by haolele123** [comment]
求拉大佬  2841938410@qq.com

**Comment by nigeiwo** [comment]
大佬求拉进群 dreamer_wan@qq.com

**Comment by PAX122** [comment]
感谢大佬，

**Comment by ustcdane** [comment]
求微信群二维码 3851234347@qq.com @wangzhaode

**Comment by ydliou** [comment]
同求 yd.liou@outlook.com

**Comment by mujica-oblivionis** [comment]
大佬，求拉进群578346565@qq.com， 感谢
