### ISSUE TITLE
有没有预构建二进制文件

### ISSUE THREAD

**Issue by YIZXIY** [wangzhaode/mnn-llm#6]
有没有预构建二进制文件（编译好现成的），凡夫俗子编译一遍实在折寿，一直报错，解决一个出来一堆

**Comment by wangzhaode** [comment]
目前还没有 可以提供图编译的包 但是MNN with cuda 需要自己编译

**Comment by wangzhaode** [comment]
https://github.com/wangzhaode/ChatGLM-MNN/releases/tag/v0.5

**Comment by zx2021** [comment]
> 这里提供了一下Linux和Android的预编译包，Linux有CUDA依赖： https://github.com/wangzhaode/ChatGLM-MNN/releases/tag/v0.5

很好
但是有windows10 cuda的预编译包吗
