### ISSUE TITLE
有没有考虑把 GLM-6B中的 tokenizer 改写成 C++ 呢 ？

### ISSUE THREAD

**Issue by sgxu** [wangzhaode/mnn-llm#61]
有没有考虑把 GLM-6B中的 tokenizer 改写成 C++ 呢 ？
jieba 好像不太好对齐

**Comment by wangzhaode** [comment]
可以作为后续计划

**Comment by tylike** [comment]
我有点疑问，chatglm-6b在python中用的中sentencePiece做分词的，这里改成了jieba，还是可以用的？
