### ISSUE TITLE
windows全部使用CPU部署加载模型时出错

### ISSUE THREAD

**Issue by WalkeR-ZG** [wangzhaode/mnn-llm#69]
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/25215530/f6dbb389-2c23-4794-95bf-f2f1f2ded5b3)

**Comment by WalkeR-ZG** [comment]
一样的错误~

**Comment by HaviZou** [comment]
![屏幕截图 2023-06-06 075635](https://github.com/wangzhaode/ChatGLM-MNN/assets/134673183/524dde49-e45d-4921-9a24-4d02382df74e)
![屏幕截图 2023-06-06 080020](https://github.com/wangzhaode/ChatGLM-MNN/assets/134673183/b78fd491-d136-40ae-a153-4361ffd0641a)

c++ runtime 都加载了  还是有相同的错误
