### ISSUE TITLE
推断速度比较慢

### ISSUE THREAD

**Issue by dayu1979** [wangzhaode/mnn-llm#7]
虽然显存占用接近8个G，但是我发现推断的时候gpu的占用很低，显然并没有完全利用到gpu，而且速度比较慢。不知道什么原因。

**Comment by wangzhaode** [comment]
实测速度如何，应该能达到每秒3word以上吧？

目前还没有做量化 8G显存不能全部放下所有模型 所以分段放进一部分到显卡中，另一部分在CPU计算；因为整个模型是串行执行的，CPU计算时显卡是没有计算的，所以显卡占用率确实不高；

**Comment by wangzhaode** [comment]
你的测试硬件和速度能发一下嘛

**Comment by FrostMiKu** [comment]
慢的有点离谱了，感觉就像是纯用cpu算的，int4量化用pytorch 2060ti 6G 显存大概能一秒钟3个字，用这个的话40多秒出来一个字，显存和内存（16G）都占满了，很怪。

**Comment by anyshu** [comment]
比原生chatglm-6b的还要慢，是哪里要特殊设置吗？

**Comment by couldn** [comment]
这么慢那还不如Python GPU部署呢
