### ISSUE TITLE
MNN/build/express下没有*.so文件，请问一下这个模型支持AMD的GPU嘛

### ISSUE THREAD

**Issue by Luohui1028** [wangzhaode/mnn-llm#78]
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/113084654/a33c38d4-003a-4d30-9edf-482ff0133825)
如图，在MNN编译后express下没有*.so文件

**Comment by Luohui1028** [comment]
express目录下只有这些文件 
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/113084654/484b13aa-6b78-43c5-9cc5-1be401c27020)

**Comment by wangzhaode** [comment]
编译MNN使用的宏是什么样的？

使用OpenCL后端可以支持AMD GPU;

**Comment by Luohui1028** [comment]
你好，MNN的宏文件未修改过 直接使用的是你代码中的
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/113084654/64d404ff-0532-4124-ab9e-71388b7c90e2)
，这里是一些编译中的信息，也能看到openCL是on状态，
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/113084654/e7b99dc3-07d3-42cb-981b-840f8847b1f2)
请问一下express下没有.so文件与使用容器是否有关呢，谢谢~

**Comment by Luohui1028** [comment]
> 哦 `-DMNN_SEP_BUILD=ON` 时候会把express的库编译到`libMNN.so`里，就不需要`libMNN_Express.so`了

感谢~~ 在MNN编译时我们使用`cmake -DCMAKE_BUILD_TYPE=Release -DMNN_OPENCL=ON -DMNN_USE_SYSTEM_LIB=ON -DMNN_SEP_BUILD=ON ..` 命令，并且没有复制 libMNN_Express.so文件，但是最后编译ChatGLM-MNN时招不到cuda，请教一下可能是什么原因呢
![1dd358f1e36e35f231616c117a4daca](https://github.com/wangzhaode/ChatGLM-MNN/assets/113084654/cf4c5ca4-aebb-4016-b251-eb3a1aca4eb3)

**Comment by YouCii** [comment]
刚开始没有，重试了一次出现了 libMNN_Express.dylib，但是android编译时仍然提示缺失：library not found for -llog

**Comment by gaolongxi** [comment]
> 刚开始没有，重试了一次出现了 libMNN_Express.dylib，但是android编译时仍然提示缺失：library not found for -llog

请问你解决了吗？我在mac上面编译mnn库生成的是.dylib而不是.so，后续想要android编译的时候，运行make -j8命令后报错：
