### ISSUE TITLE
编译成功，执行时出错，C++库已全部安装，仍报错

### ISSUE THREAD

**Issue by HaviZou** [wangzhaode/mnn-llm#80]
使用模式: cpu  int8 win10 
![屏幕截图 2023-06-06 102018](https://github.com/wangzhaode/ChatGLM-MNN/assets/134673183/ec92b8ff-ba34-424c-9424-c512eaa39015)
![屏幕截图 2023-06-06 102421](https://github.com/wangzhaode/ChatGLM-MNN/assets/134673183/527e8027-a223-4af8-90fb-435694e52fe7)

**Comment by linzaixing** [comment]
遇到和楼主一样的问题，windows环境下编译通过，但是运行报错
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/50514350/1179ae39-5825-4680-97de-798283c61e36)

**Comment by linzaixing** [comment]
> 遇到和楼主一样的问题，windows环境下编译通过，但是运行报错 ![image](https://user-images.githubusercontent.com/50514350/266796336-1179ae39-5825-4680-97de-798283c61e36.png)

在另外一个帖子中解决了：Can't Find type=2 backend, use 3 instead
1. var = _Reshape(var, {HIDDEN_SIZE, 1});
2. VARP ChatGLM::gen_embedding(const std::vector<int> &input_ids) { 
    size_t seq_len = input_ids.size(); 
    auto embedding_var = _Input({static_cast<int>(seq_len), 1, HIDDEN_SIZE}, NCHW); 
    constexpr size_t size = HIDDEN_SIZE * sizeof(float); 
    FILE *file = fopen("../resource/models/fp16/slim_word_embeddings.bin", "rb"); 
    for (size_t i = 0; i < seq_len; i++) { 
        fseek(file, input_ids[i] * size, SEEK_SET); 
        fread(embedding_var->writeMap<char>() + i * size, 1, size, file); 
    } 
    fclose(file); 
    return embedding_var; 
}

但是现在回答问题出现乱码：
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/50514350/95a50c78-ced5-4133-970c-ab467504aa80)
最后吐槽一下：别人才过的坑为什么不提交修复呀，代码不维护了吗
