### ISSUE TITLE
Can't Find type=2 backend, use 3 instead

### ISSUE THREAD

**Issue by liao0028** [wangzhaode/mnn-llm#82]
MI210显卡最后一步运行时load_model出现错误

![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/51874538/aa54037f-8ba8-4bcb-b092-ce3d62051408)

**Comment by HaviZou** [comment]
模型路径是不是不对？查看下文件夹，默认下载好像在下一层文件夹(fp16 int4 int8),把模型文件copy出来试试

**Comment by DeRong-He** [comment]
修改路径后加载成功了，但是回答时显示错误Segmentation fault (core dumped)，应该forward函数部分出了问题？
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/51874538/91126404-11d4-4d62-b09a-f16890544ac8)

**Comment by DeRong-He** [comment]
问题定位到这一步，找不到解决办法了。
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/51874538/107eb890-b2f7-4f4d-8b07-012d964f1a76)

**Comment by tal-108767** [comment]
运行发现同样问题，关注！

**Comment by wangzhaode** [comment]
> @wangzhaode 发现是lm_head层的期望输入形状是[4096,1]，将var向量转为该形状后可以运行，但是生成的都是unk字段。
> 
> ![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/51874538/1aaf2c27-8cd0-451d-b701-b6a72e2a620d)
> 
> 

更新一下代码哈 有一次修改可能搞错了 最新代码用int4 release下的模型试试看

**Comment by DeRong-He** [comment]
> > @wangzhaode 发现是lm_head层的期望输入形状是[4096,1]，将var向量转为该形状后可以运行，但是生成的都是unk字段。
> > ![image](https://user-images.githubusercontent.com/51874538/243684536-1aaf2c27-8cd0-451d-b701-b6a72e2a620d.png)
> 
> 更新一下代码哈 有一次修改可能搞错了 最新代码用int4 release下的模型试试看

已经用最新代码且换成int4模型，但仍出现同样的问题，lm_head层的期望输入形状仍是[4096,1]，输出仍是unk字段。

**Comment by Lacacy** [comment]
@DeRong-He   我在别人fork的仓库之中发现了该bug的具体问题，以及解决方式；

1. 你提到的 发现是lm_head层的期望输入形状是[4096,1]，将var向量转为该形状后可以运行，但是生成的都是unk字段。
按照你的截图解决即可；

2. gen_embedding 替换为我提供的函数，并且确认你的文件是否存在之后，在重现编译，运行程序:
`VARP ChatGLM::gen_embedding(const std::vector<int> &input_ids) {
    size_t seq_len = input_ids.size();
    auto embedding_var = _Input({static_cast<int>(seq_len), 1, HIDDEN_SIZE}, NCHW);
    constexpr size_t size = HIDDEN_SIZE * sizeof(float);
    FILE *file = fopen("../resource/models/int8/slim_word_embeddings.bin", "rb");
    for (size_t i = 0; i < seq_len; i++) {
        fseek(file, input_ids[i] * size, SEEK_SET);
        fread(embedding_var->writeMap<char>() + i * size, 1, size, file);
    }
    fclose(file);
    return embedding_var;
}`

这两步之后，程序即可正常工作；

**Comment by DeRong-He** [comment]
> @DeRong-He 我在别人fork的仓库之中发现了该bug的具体问题，以及解决方式；
> 
> 1. 你提到的 发现是lm_head层的期望输入形状是[4096,1]，将var向量转为该形状后可以运行，但是生成的都是unk字段。
>    按照你的截图解决即可；
> 2. gen_embedding 替换为我提供的函数，并且确认你的文件是否存在之后，在重现编译，运行程序:
>    `VARP ChatGLM::gen_embedding(const std::vector<int> &input_ids) { size_t seq_len = input_ids.size(); auto embedding_var = _Input({static_cast<int>(seq_len), 1, HIDDEN_SIZE}, NCHW); constexpr size_t size = HIDDEN_SIZE * sizeof(float); FILE *file = fopen("../resource/models/int8/slim_word_embeddings.bin", "rb"); for (size_t i = 0; i < seq_len; i++) { fseek(file, input_ids[i] * size, SEEK_SET); fread(embedding_var->writeMap<char>() + i * size, 1, size, file); } fclose(file); return embedding_var; }`
> 
> 这两步之后，程序即可正常工作；

感谢回复，刚试了一下，已经可以正常解析字段，但最后还是会多输出一个epo字段，而且速度不到1toekn/s。目前我已转用https://github.com/ztxz16/fastllm，并成功移植部署到了A卡MI210上，在int8模型下，速度达到了51token/s。
