### ISSUE TITLE
ChatGLM-MNN推理速度慢，是需要开启什么配置么？

### ISSUE THREAD

**Issue by oncealong** [wangzhaode/mnn-llm#84]
fastllm是指"https://github.com/ztxz16/fastllm"
用的是int4量化版本。
内存占用比fastllm大3倍左右，导致手机端必须开启小内存模式。但是小内存模式，耗时又在io加载模型上比较多。

在电脑上内存大3倍的情况下，推理速度仍然没有fastllm快，请问是需要开启什么参数设置么？

**Comment by wangzhaode** [comment]
最新优化的MNN代码还未同步 等待下次版本发布会更新 麻烦您再等等

**Comment by oncealong** [comment]
> 

请问内存占用大是因为 MNN还不支持 量化下模型推理么？
