### ISSUE TITLE
提问时崩溃  如何调试呢

### ISSUE THREAD

**Issue by HJT9328** [wangzhaode/mnn-llm#86]
docker  运行时启动cli_demo显示如下

Compute capability: 7.0
GPU Device supports FP16 computation
Total global memory: 31.7485G
Total available memory: 31.1509G
model path is ../resource/models
The device support dot:0, support fp16:0, support i8mm: 0
load ../resource/tokenizer/slim_vocab.txt ... Done!
load ../resource/models/lm.mnn model ... Done!
[  8% ] load ../resource/models/glm_block_0.mnn model ... Done!
[ 12% ] load ../resource/models/glm_block_1.mnn model ... Done!
[ 15% ] load ../resource/models/glm_block_2.mnn model ... Done!
[ 18% ] load ../resource/models/glm_block_3.mnn model ... Done!
[ 22% ] load ../resource/models/glm_block_4.mnn model ... Done!
[ 25% ] load ../resource/models/glm_block_5.mnn model ... Done!
[ 28% ] load ../resource/models/glm_block_6.mnn model ... Done!
[ 31% ] load ../resource/models/glm_block_7.mnn model ... Done!
[ 35% ] load ../resource/models/glm_block_8.mnn model ... Done!
[ 38% ] load ../resource/models/glm_block_9.mnn model ... Done!
[ 41% ] load ../resource/models/glm_block_10.mnn model ... Done!
[ 44% ] load ../resource/models/glm_block_11.mnn model ... Done!
[ 48% ] load ../resource/models/glm_block_12.mnn model ... Done!
[ 51% ] load ../resource/models/glm_block_13.mnn model ... Done!
[ 54% ] load ../resource/models/glm_block_14.mnn model ... Done!
[ 58% ] load ../resource/models/glm_block_15.mnn model ... Done!
[ 61% ] load ../resource/models/glm_block_16.mnn model ... Done!
[ 64% ] load ../resource/models/glm_block_17.mnn model ... Done!
[ 67% ] load ../resource/models/glm_block_18.mnn model ... Done!
[ 71% ] load ../resource/models/glm_block_19.mnn model ... Done!
[ 74% ] load ../resource/models/glm_block_20.mnn model ... Done!
[ 77% ] load ../resource/models/glm_block_21.mnn model ... Done!
[ 80% ] load ../resource/models/glm_block_22.mnn model ... Done!
[ 84% ] load ../resource/models/glm_block_23.mnn model ... Done!
[ 87% ] load ../resource/models/glm_block_24.mnn model ... Done!
[ 90% ] load ../resource/models/glm_block_25.mnn model ... Done!
[ 93% ] load ../resource/models/glm_block_26.mnn model ... Done!
[ 97% ] load ../resource/models/glm_block_27.mnn model ... Done!
[100% ] 
Q: hello

A: Segmentation fault (core dumped)

感觉是内存出了问题，但是没有core文件 这时应该如何调试呢

**Comment by HJT9328** [comment]
机器V100 模型已经加载到显存中 但是对话时崩溃了

**Comment by pengpansxy** [comment]
我也这样

**Comment by skywalk163** [comment]
俺也一样

**Comment by I0me0I** [comment]
我也出现过`Segmentation fault`，似乎embedding的文件名错了
`src/chat.cpp`第`191`行：
```c++
std::string file_path = mModelDir + "/slim_word_embeddings_bf16.bin";
```
改为：
```c++
std::string file_path = mModelDir + "/slim_word_embeddings.bin";
```
之后重新bulid，不再报同样的错了
但是我的机器又出现了`Compute Shape Error for MatMul3`
应该是我的机器发生了别的问题

**Comment by I0me0I** [comment]
下载脚本似乎也有误，详见：https://github.com/wangzhaode/ChatGLM-MNN/issues/92#issuecomment-1607734393

**Comment by skywalk163** [comment]
按照楼上修改了文件名，也出现那个shape error了 ：
```
A: Compute Shape Error for MatMul3
Can't run session because not resized
段错误 (核心已转储)
```

**Comment by skywalk163** [comment]
问题解决，总体的解决方法：
1 下载92号issue里面某朋友讲的bf16的embedding权重，这个权重文件可以在这里下载：https://github.com/wangzhaode/ChatGLM-MNN/releases/download/v0.3/slim_word_embeddings_bf16.bin
2 将chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {HIDDEN_SIZE, 1});
