### ISSUE TITLE
Segmentation fault when inference with int4/int8

### ISSUE THREAD

**Issue by Lqlsoftware** [wangzhaode/mnn-llm#88]
I've compiled MNN 2.5.0 correctly (with ARMv8.2), and it occurred when starting inference with both int4/int8 models.

`model path is ../resource/models
hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Can't Find type=2 backend, use 3 instead
load ../resource/tokenizer/slim_vocab.txt ... Done!
load ../resource/models/lm.mnn model ... Done!
[  8% ] load ../resource/models/glm_block_0.mnn model ... Done!
[ 12% ] load ../resource/models/glm_block_1.mnn model ... Done!
[ 15% ] load ../resource/models/glm_block_2.mnn model ... Done!
[ 18% ] load ../resource/models/glm_block_3.mnn model ... Done!
[ 22% ] load ../resource/models/glm_block_4.mnn model ... Done!
[ 25% ] load ../resource/models/glm_block_5.mnn model ... Done!
[ 28% ] load ../resource/models/glm_block_6.mnn model ... Done!
[ 31% ] load ../resource/models/glm_block_7.mnn model ... Done!
[ 35% ] load ../resource/models/glm_block_8.mnn model ... Done!
[ 38% ] load ../resource/models/glm_block_9.mnn model ... Done!
[ 41% ] load ../resource/models/glm_block_10.mnn model ... Done!
[ 44% ] load ../resource/models/glm_block_11.mnn model ... Done!
[ 48% ] load ../resource/models/glm_block_12.mnn model ... Done!
[ 51% ] load ../resource/models/glm_block_13.mnn model ... Done!
[ 54% ] load ../resource/models/glm_block_14.mnn model ... Done!
[ 58% ] load ../resource/models/glm_block_15.mnn model ... Done!
[ 61% ] load ../resource/models/glm_block_16.mnn model ... Done!
[ 64% ] load ../resource/models/glm_block_17.mnn model ... Done!
[ 67% ] load ../resource/models/glm_block_18.mnn model ... Done!
[ 71% ] load ../resource/models/glm_block_19.mnn model ... Done!
[ 74% ] load ../resource/models/glm_block_20.mnn model ... Done!
[ 77% ] load ../resource/models/glm_block_21.mnn model ... Done!
[ 80% ] load ../resource/models/glm_block_22.mnn model ... Done!
[ 84% ] load ../resource/models/glm_block_23.mnn model ... Done!
[ 87% ] load ../resource/models/glm_block_24.mnn model ... Done!
[ 90% ] load ../resource/models/glm_block_25.mnn model ... Done!
[ 93% ] load ../resource/models/glm_block_26.mnn model ... Done!
[ 97% ] load ../resource/models/glm_block_27.mnn model ... Done!
[100% ]
Q: Hello

A: [1]    31272 segmentation fault  ./cli_demo

`

**Comment by zhufuwengang** [comment]
hi , have you fix this issue?

**Comment by I0me0I** [comment]
I've got the same problem.

Change the line 191 of `src/chat.cpp` from：
```c++
std::string file_path = mModelDir + "/slim_word_embeddings_bf16.bin";
```
to：
```c++
std::string file_path = mModelDir + "/slim_word_embeddings.bin";
```
and rebuild may fix it, but cause another problem on my machine.
Maybe it will works on your machine.

**Comment by Lqlsoftware** [comment]
> hi , have you fix this issue?

Int4 is still not, and int8 model now working by solution: https://github.com/wangzhaode/ChatGLM-MNN/issues/92#issuecomment-1611222843

**Comment by Lqlsoftware** [comment]
> Download script seems incorrect. The fp16 model and int8 model supposed to use v0.1(fp16) `lm.mnn` and `slim_word_embeddings.bin` The int4 model supposed to use v0.3(int4) `lm.mnn` and `slim_word_embeddings_bf16.bin` But in download script, all of them use v0.1(fp16) `lm.mnn` and `slim_word_embeddings.bin`

Thks, I see the difference of word_embeddings_bf16~
