### ISSUE TITLE
GPU显存占用上去，运算并没有使用GPU，推理速度30s/字

### ISSUE THREAD

**Issue by xu-mengnan** [wangzhaode/mnn-llm#89]
<img width="579" alt="图片" src="https://github.com/wangzhaode/ChatGLM-MNN/assets/36294047/c274e14e-254a-43f7-8d6c-12a6e26e3349">

按照教程来进行的配置安装，但是发现推理速度非常慢。
机器配置：2080ti/8G显存/5CPU/12G内存。
模型：GLM int4

**Comment by wangzhaode** [comment]
MNN编译时是否开启了CUDA选项呢

**Comment by xu-mengnan** [comment]
> MNN编译时是否开启了CUDA选项呢

<img width="839" alt="图片" src="https://github.com/wangzhaode/ChatGLM-MNN/assets/36294047/da22093a-754b-4784-9b48-271d90481fc1">
除了这两项，还需要进行其他的额外配置吗
