### ISSUE TITLE
linux上运行int4模型失败---Segmentation fault

### ISSUE THREAD

**Issue by zhufuwengang** [wangzhaode/mnn-llm#92]
linux上使用cuda运行int4模型，提问时内存占满，生成回答失败,报Segmentation fault

内存: 256G
显存: 32M

model path is ../resource/models
The device support i8sdot:0, support fp16:0, support i8mm: 0
Can't Find type=2 backend, use 3 instead
load ../resource/tokenizer/slim_vocab.txt ... Done!
load ../resource/models/lm.mnn model ... Acquire buffer size = 0
Not Enough Memory
Done!

[  8% ] load ../resource/models/glm_block_0.mnn model ... Done!
[ 12% ] load ../resource/models/glm_block_1.mnn model ... Done!
[ 15% ] load ../resource/models/glm_block_2.mnn model ... Done!
[ 18% ] load ../resource/models/glm_block_3.mnn model ... Done!
[ 22% ] load ../resource/models/glm_block_4.mnn model ... Done!
[ 25% ] load ../resource/models/glm_block_5.mnn model ... Done!
[ 28% ] load ../resource/models/glm_block_6.mnn model ... Done!
[ 31% ] load ../resource/models/glm_block_7.mnn model ... Done!
[ 35% ] load ../resource/models/glm_block_8.mnn model ... Done!
[ 38% ] load ../resource/models/glm_block_9.mnn model ... Done!
[ 41% ] load ../resource/models/glm_block_10.mnn model ... Done!
[ 44% ] load ../resource/models/glm_block_11.mnn model ... Done!
[ 48% ] load ../resource/models/glm_block_12.mnn model ... Done!
[ 51% ] load ../resource/models/glm_block_13.mnn model ... Done!
[ 54% ] load ../resource/models/glm_block_14.mnn model ... Done!
[ 58% ] load ../resource/models/glm_block_15.mnn model ... Done!
[ 61% ] load ../resource/models/glm_block_16.mnn model ... Done!
[ 64% ] load ../resource/models/glm_block_17.mnn model ... Done!
[ 67% ] load ../resource/models/glm_block_18.mnn model ... Done!
[ 71% ] load ../resource/models/glm_block_19.mnn model ... Done!
[ 74% ] load ../resource/models/glm_block_20.mnn model ... Done!
[ 77% ] load ../resource/models/glm_block_21.mnn model ... Done!
[ 80% ] load ../resource/models/glm_block_22.mnn model ... Done!
[ 84% ] load ../resource/models/glm_block_23.mnn model ... Done!
[ 87% ] load ../resource/models/glm_block_24.mnn model ... Done!
[ 90% ] load ../resource/models/glm_block_25.mnn model ... Done!
[ 93% ] load ../resource/models/glm_block_26.mnn model ... Done!
[ 97% ] load ../resource/models/glm_block_27.mnn model ... Done!
[100% ] 
Q: hello

A:Acquire buffer size = 0
Not Enough Memory
Can't run session because not resized
Segmentation fault

**Comment by zhufuwengang** [comment]
Segmentation fault的原因是var_to_token里面，没有校验mModules.back()->onForward({var});的返回值，在onForward异常时，返回空指针，在int id = outputs[0]->readMap<int>()[0];时，直接段错误。

**Comment by I0me0I** [comment]
我也出现过`Segmentation fault`，似乎embedding的文件名错了
`src/chat.cpp`第`191`行：
```c++
std::string file_path = mModelDir + "/slim_word_embeddings_bf16.bin";
```
改为：
```c++
std::string file_path = mModelDir + "/slim_word_embeddings.bin";
```
之后重新bulid，不再报同样的错了
但是我的机器又出现了`Compute Shape Error for MatMul3`
应该是发生了别的问题

**Comment by zhufuwengang** [comment]
这个地方确实是个问题。int4 的download脚本下载的是v0.3的glm_block_xx.mnn，以及v0.1的slim_word_embeddings.bin。所以，chat.cpp里面感觉确实需要改为slim_word_embeddings.bin
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/24954820/3af15aa1-e880-48c3-a97b-a014bceebc9c)

我改了chat.cpp后，依然会在相同的位置断错误。

**Comment by zhufuwengang** [comment]
> 
你把chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {1, HIDDEN_SIZE, 1});试试。

**Comment by zhufuwengang** [comment]
> 我也出现过`Segmentation fault`，似乎embedding的文件名错了 `src/chat.cpp`第`191`行：
> 
> ```c++
> std::string file_path = mModelDir + "/slim_word_embeddings_bf16.bin";
> ```
> 
> 改为：
> 
> ```c++
> std::string file_path = mModelDir + "/slim_word_embeddings.bin";
> ```
> 
> 之后重新bulid，不再报同样的错了 但是我的机器又出现了`Compute Shape Error for MatMul3` 应该是我的机器又发生了别的问题
你把chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {1, HIDDEN_SIZE, 1});试试。

**Comment by I0me0I** [comment]
> > 你把chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {1, HIDDEN_SIZE, 1});试试。

谢谢， 我改了之后确实没报错了，但是生成的回答全是`<unk><unk><unk>`。

**Comment by Garfield-kh** [comment]
v0.1的checkpoint要搭配v0.1的代码, 好像是这样的.

**Comment by I0me0I** [comment]
> v0.1的checkpoint要搭配v0.1的代码, 好像是这样的.

下载脚本有问题吧，从Release上来看应该是
fp16和int8模型都使用v0.1(fp16)的`lm.mnn`和`slim_word_embeddings.bin`
int4模型使用v0.3(int4)的`lm.mnn`和`slim_word_embeddings_bf16.bin`
但是在下载脚本里int4, int8, fp16 都下载的是v0.1(fp16)的`lm.mnn`和`slim_word_embeddings.bin`

**Comment by I0me0I** [comment]
换了v0.3(int4)的`lm.mnn`之后，加载`lm.mnn`时的提示变了，从
```shell
load ../resource/models/lm.mnn model ... Done!
```
变成了
```shell
load ../resource/models/lm.mnn model ... Acquire buffer size = 0
Not Enough Memory
Done!
```
然后出现了和题主一样错误

**Comment by I0me0I** [comment]
另外，`cli_demo.cpp`里46行的定义的`data_type`：
```C++
    std::string data_type = "fp16";
```
始终没有使用，我一开始怀疑demo只做了fp16的版本。
但是在`chat.cpp`里面第191行
```C++
std::string file_path = mModelDir + "/slim_word_embeddings_bf16.bin";
```
调用的是v0.3(int4)的`slim_word_embeddings_bf16.bin`文件。
所以，这两个文件的版本不对，可能是没有更新或是git合并的时候出错了。

**Comment by wangzhaode** [comment]
> 我也出现过`Segmentation fault`，似乎embedding的文件名错了 `src/chat.cpp`第`191`行：
> 
> ```c++
> std::string file_path = mModelDir + "/slim_word_embeddings_bf16.bin";
> ```
> 
> 改为：
> 
> ```c++
> std::string file_path = mModelDir + "/slim_word_embeddings.bin";
> ```
> 
> 之后重新bulid，不再报同样的错了 但是我的机器又出现了`Compute Shape Error for MatMul3` 应该是我的机器又发生了别的问题

最新的代码使用bf16的embedding权重了，这个权重文件可以在这里下载：https://github.com/wangzhaode/ChatGLM-MNN/releases/download/v0.3/slim_word_embeddings_bf16.bin

**Comment by wangzhaode** [comment]
> 换了v0.3(int4)的`lm.mnn`之后，加载`lm.mnn`时的提示变了，从
> 
> ```shell
> load ../resource/models/lm.mnn model ... Done!
> ```
> 
> 变成了
> 
> ```shell
> load ../resource/models/lm.mnn model ... Acquire buffer size = 0
> Not Enough Memory
> Done!
> ```
> 
> 然后出现了和题主一样错误

请问您使用的是CUDA还是CPU ？

**Comment by zhufuwengang** [comment]
> 



> > 换了v0.3(int4)的`lm.mnn`之后，加载`lm.mnn`时的提示变了，从
> > ```shell
> > load ../resource/models/lm.mnn model ... Done!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 变成了
> > ```shell
> > load ../resource/models/lm.mnn model ... Acquire buffer size = 0
> > Not Enough Memory
> > Done!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后出现了和题主一样错误
> 
> 请问您使用的是CUDA还是CPU ？

我使用的是CPU。。。。

**Comment by I0me0I** [comment]
> 请问您使用的是CUDA还是CPU ？

在window平台用的CPU，在linux上用的GPU，硬件一样的
只要换了v0.3(1in4)的`lm.mnn`就会出现 `Acquire buffer size = 0` 这样的错误
用v0.1(fp16)的`lm.mnn`不会报这样的错

**Comment by skywalk163** [comment]
换了16位的slim_word_embeddings_bf16.bin
报错信息为
```
A: Compute Shape Error for MatMul3
Can't run session because not resized
段错误 (核心已转储)
```

**Comment by skywalk163** [comment]
换了16位的slim_word_embeddings_bf16.bin
报错信息为
```
A: Compute Shape Error for MatMul3
Can't run session because not resized
段错误 (核心已转储)
```


> > > 你把chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {1, HIDDEN_SIZE, 1});试试。
> 
> 谢谢， 我改了之后确实没报错了，但是生成的回答全是`<unk><unk><unk>`。

我改了也是回答全变成`<unk><unk><unk>`

**Comment by skywalk163** [comment]
搞定了，chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {HIDDEN_SIZE, 1});试试吧
！不懂C语言，不过是在翻ChatGLM-MNN以前版本代码，发现历史上有这种写法，拿来一试，竟然成了！

总体的解决方法：
1 安装前面朋友讲的下载bf16的embedding权重，这个权重文件可以在这里下载：https://github.com/wangzhaode/ChatGLM-MNN/releases/download/v0.3/slim_word_embeddings_bf16.bin
2 将chat.cpp 281行的var = _Reshape(var, {1, HIDDEN_SIZE, 1, 1}); 改为var = _Reshape(var, {HIDDEN_SIZE, 1});
