### ISSUE TITLE
Sementation fault

### ISSUE THREAD

**Issue by kevin945a** [wangzhaode/mnn-llm#96]
![1](https://github.com/wangzhaode/ChatGLM-MNN/assets/99779317/e9bf09e7-5744-4fd0-a7cd-6e6574b3f1b9)
我尝试修改chat.cpp，还是没有用
![2](https://github.com/wangzhaode/ChatGLM-MNN/assets/99779317/74e024a0-b9a0-421d-8ae6-4b0549ac040a)

**Comment by kevin945a** [comment]
召唤大神！！i need your help

**Comment by wangzhaode** [comment]
用int4的模型测试一下看看:
https://github.com/wangzhaode/ChatGLM-MNN/releases/tag/v0.3

**Comment by kevin945a** [comment]
![Uploading e4d8daba3422634b7712764ce65aea9.png…]()

**Comment by wangzhaode** [comment]
> ![1](https://user-images.githubusercontent.com/99779317/250494781-e9bf09e7-5744-4fd0-a7cd-6e6574b3f1b9.png) 我尝试修改chat.cpp，还是没有用 ![2](https://user-images.githubusercontent.com/99779317/250495101-74e024a0-b9a0-421d-8ae6-4b0549ac040a.png)

不要改代码，需要重新下载一下embedding的数据文件

**Comment by wangzhaode** [comment]
看一下这个文件下载了嘛：
https://github.com/wangzhaode/ChatGLM-MNN/releases/download/v0.3/slim_word_embeddings_bf16.bin

**Comment by kevin945a** [comment]
我没改代码，等一下，好像int4的slim_word的文件不一样

**Comment by wangzhaode** [comment]
这个文件也需要下载：
https://github.com/wangzhaode/ChatGLM-MNN/releases/download/v0.3/lm.mnn

**Comment by wangzhaode** [comment]
建议是重新从int4那个列表下载一下模型文件哈

**Comment by kevin945a** [comment]
okok
我全重下一遍试试，我这个最高能使用int8的是吧

**Comment by wangzhaode** [comment]
> okok 我全重下一遍试试，我这个最高能使用int8的是吧

也能用int8 不过lm.mnn 和 embedding的数据需要用int4这个release里提供的

**Comment by kevin945a** [comment]
okok

**Comment by kevin945a** [comment]
根据你的指导下载了模型，还是报错，这回报错不一样了
![1](https://github.com/wangzhaode/ChatGLM-MNN/assets/99779317/51c3a847-6599-42a3-ab8a-4376215d0736)

**Comment by kevin945a** [comment]
![2](https://github.com/wangzhaode/ChatGLM-MNN/assets/99779317/302785d7-df43-4bff-9e5c-addb1a4956a9)
![3](https://github.com/wangzhaode/ChatGLM-MNN/assets/99779317/88c8debe-a313-4f99-b9ed-08edd7d91223)
help！！

**Comment by wangzhaode** [comment]
请问你用CPU跑的还是CPU + GPU ？

**Comment by kevin945a** [comment]
gpu 跑啊

**Comment by kevin945a** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DMNN_CUDA=ON ..
我好像选的这个

**Comment by kevin945a** [comment]
我刚刚试了一下cpu
编译MNN库
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j4

编译ChatGLM-MNN
cmake ..
make -j4

还是报一样的错误：Acquire buffer size = 0 Not Enough Memory

**Comment by kevin945a** [comment]
召唤大神！！召唤大神！！！ @wangzhaode

**Comment by wangzhaode** [comment]
> 我刚刚试了一下cpu 编译MNN库 cmake -DCMAKE_BUILD_TYPE=Release .. make -j4
> 
> 编译ChatGLM-MNN cmake .. make -j4
> 
> 还是报一样的错误：Acquire buffer size = 0 Not Enough Memory

你使用最新的MNN代码试试

**Comment by wangzhaode** [comment]
不应该的啊 我这里测试没问题

**Comment by kevin945a** [comment]
最新的是2.5吧 我好像就是用的2.5 我再重新下个试试
